export type AestheticCategory =
  | 'todos'
  | 'corazones'
  | 'estrellas'
  | 'brillos'
  | 'lunas'
  | 'flores'
  | 'lazos'
  | 'flechas'
  | 'separadores'
  | 'marcos'
  | 'musica'
  | 'naturaleza'
  | 'cute'
  | 'coquette'
  | 'minimalistas';

export interface AestheticSymbol {
  id: string;
  symbol: string;
  name: string;
  categories: AestheticCategory[];
  tags: string[];
  aliases: string[];
  featured?: boolean;
  comboEligible?: boolean;
}

export interface AestheticReadyCombo {
  id: string;
  combo: string;
  name: string;
  useCase: 'nombres' | 'bios' | 'separadores' | 'minimalistas-coquette';
  tags: string[];
}

export const AESTHETIC_CATEGORIES: { id: AestheticCategory; label: string; icon: string }[] = [
  { id: 'todos', label: 'Todos', icon: '✨' },
  { id: 'corazones', label: 'Corazones', icon: '♡' },
  { id: 'estrellas', label: 'Estrellas', icon: '★' },
  { id: 'brillos', label: 'Brillos', icon: '✦' },
  { id: 'lunas', label: 'Lunas', icon: '☾' },
  { id: 'flores', label: 'Flores', icon: '✿' },
  { id: 'lazos', label: 'Lazos', icon: '୨୧' },
  { id: 'flechas', label: 'Flechas', icon: '→' },
  { id: 'separadores', label: 'Separadores', icon: '─' },
  { id: 'marcos', label: 'Marcos', icon: '『』' },
  { id: 'musica', label: 'Música', icon: '♫' },
  { id: 'naturaleza', label: 'Naturaleza', icon: '☘' },
  { id: 'cute', label: 'Cute', icon: 'ฅ' },
  { id: 'coquette', label: 'Coquette', icon: '𐙚' },
  { id: 'minimalistas', label: 'Minimalistas', icon: '·' },
];

export const AESTHETIC_SYMBOLS: AestheticSymbol[] = [
  // ── Corazones & Cute Romance ──
  {
    id: 'aes-heart-white',
    symbol: '♡',
    name: 'Corazón Contorno Blanco',
    categories: ['corazones', 'cute', 'minimalistas'],
    tags: ['amor', 'romantico', 'romántico', 'suave', 'tierno'],
    aliases: ['corazon', 'corazón', 'heart', 'love', 'blanco'],
    featured: true,
    comboEligible: true,
  },
  {
    id: 'aes-heart-black',
    symbol: '♥',
    name: 'Corazón Sólido Negro',
    categories: ['corazones', 'cute'],
    tags: ['amor', 'pareja', 'oscuro', 'clásico'],
    aliases: ['corazon negro', 'corazón negro', 'black heart'],
    featured: true,
    comboEligible: true,
  },
  {
    id: 'aes-heart-red',
    symbol: '❤',
    name: 'Corazón Rojo Clásico',
    categories: ['corazones', 'cute'],
    tags: ['amor', 'pasion', 'pasión', 'rojo'],
    aliases: ['corazon rojo', 'red heart'],
    comboEligible: true,
  },
  {
    id: 'aes-heart-suit',
    symbol: '❥',
    name: 'Corazón Rotado Elegante',
    categories: ['corazones', 'cute', 'coquette'],
    tags: ['estilo', 'adorno', 'delicado'],
    aliases: ['corazon curvo', 'corazon de lado'],
    comboEligible: true,
  },
  {
    id: 'aes-heart-exclam',
    symbol: '❣',
    name: 'Corazón Exclamación',
    categories: ['corazones', 'cute'],
    tags: ['exclamacion', 'alegre'],
    aliases: ['corazon punto', 'signo corazon'],
    comboEligible: true,
  },
  {
    id: 'aes-heart-curved',
    symbol: 'ღ',
    name: 'Corazón Georgiano Suave',
    categories: ['corazones', 'coquette', 'cute', 'minimalistas'],
    tags: ['romantico', 'romántico', 'antiguo', 'femenino'],
    aliases: ['corazon georgiano', 'ghal'],
    featured: true,
    comboEligible: true,
  },
  {
    id: 'aes-heart-kannada',
    symbol: 'ಌ',
    name: 'Corazón Doble Kannada',
    categories: ['corazones', 'cute'],
    tags: ['curva', 'ornamento'],
    aliases: ['corazon kannada'],
    comboEligible: true,
  },
  {
    id: 'aes-heart-floral',
    symbol: '❦',
    name: 'Corazón Floral Hiedra',
    categories: ['corazones', 'flores', 'coquette'],
    tags: ['vintage', 'botanico', 'botánico'],
    aliases: ['hoja corazon', 'hiedra corazon'],
    comboEligible: true,
  },
  {
    id: 'aes-heart-malayalam',
    symbol: 'ෆ',
    name: 'Corazón Malayalam Tierno',
    categories: ['corazones', 'cute', 'coquette'],
    tags: ['tierno', 'korean', 'aesthetic'],
    aliases: ['corazon coreano', 'fa'],
    featured: true,
    comboEligible: true,
  },
  {
    id: 'aes-heart-sparkle',
    symbol: '💖',
    name: 'Corazón Brillante',
    categories: ['corazones', 'brillos', 'cute'],
    tags: ['brillo', 'destello', 'rosa', 'destellante'],
    aliases: ['corazon con brillos', 'sparkling heart'],
    featured: true,
    comboEligible: true,
  },
  {
    id: 'aes-heart-ribbon',
    symbol: '💝',
    name: 'Corazón con Lazo',
    categories: ['corazones', 'lazos', 'coquette'],
    tags: ['regalo', 'lazo', 'cinta', 'coquette'],
    aliases: ['corazon regalo', 'corazon lazo'],
    comboEligible: true,
  },
  {
    id: 'aes-heart-white-emoji',
    symbol: '🤍',
    name: 'Corazón Blanco Puro',
    categories: ['corazones', 'minimalistas'],
    tags: ['paz', 'limpio', 'blanco', 'puro'],
    aliases: ['white heart', 'corazon blanco'],
    comboEligible: true,
  },
  {
    id: 'aes-heart-cherub',
    symbol: 'დ',
    name: 'Corazón Suave Cherub',
    categories: ['corazones', 'coquette'],
    tags: ['ángel', 'angelical', 'tierno'],
    aliases: ['cherub', 'corazon georgiano doni'],
    comboEligible: true,
  },
  {
    id: 'aes-heart-loop',
    symbol: 'യ',
    name: 'Lazo Corazón Ya',
    categories: ['corazones', 'lazos', 'coquette'],
    tags: ['bucle', 'cinta', 'sutil'],
    aliases: ['lazo corazon', 'bucle ya'],
    comboEligible: true,
  },

  // ── Estrellas & Brillos (Sparkles) ──
  {
    id: 'aes-star-solid',
    symbol: '★',
    name: 'Estrella Sólida',
    categories: ['estrellas', 'minimalistas'],
    tags: ['noche', 'cielo', 'brillante'],
    aliases: ['estrella', 'star', 'estrella negra'],
    featured: true,
    comboEligible: true,
  },
  {
    id: 'aes-star-outline',
    symbol: '☆',
    name: 'Estrella Contorno',
    categories: ['estrellas', 'minimalistas'],
    tags: ['vacia', 'vacía', 'linea', 'blanca'],
    aliases: ['estrella blanca', 'white star', 'estrella vacia'],
    featured: true,
    comboEligible: true,
  },
  {
    id: 'aes-sparkle-4',
    symbol: '✦',
    name: 'Destello Cuatro Puntas Sólido',
    categories: ['brillos', 'estrellas', 'minimalistas'],
    tags: ['brillo', 'magia', 'aesthetic', 'destello'],
    aliases: ['brillo', 'destello', 'sparkle', 'shine', 'glow'],
    featured: true,
    comboEligible: true,
  },
  {
    id: 'aes-sparkle-4-outline',
    symbol: '✧',
    name: 'Destello Cuatro Puntas Contorno',
    categories: ['brillos', 'estrellas', 'minimalistas'],
    tags: ['brillo', 'suave', 'sutil', 'magia'],
    aliases: ['destello blanco', 'brillo fino'],
    featured: true,
    comboEligible: true,
  },
  {
    id: 'aes-star-small',
    symbol: '⋆',
    name: 'Estrella Pequeña Operador',
    categories: ['estrellas', 'brillos', 'minimalistas'],
    tags: ['polvo', 'estelar', 'cosmico', 'cósmico'],
    aliases: ['estrellita', 'punto estrella', 'starlet'],
    featured: true,
    comboEligible: true,
  },
  {
    id: 'aes-star-sparkle-diamond',
    symbol: '⟡',
    name: 'Diamante con Destello',
    categories: ['brillos', 'estrellas', 'minimalistas'],
    tags: ['joya', 'diamante', 'cristal'],
    aliases: ['diamante', 'joya', 'cristal'],
    comboEligible: true,
  },
  {
    id: 'aes-star-arabic',
    symbol: '⭒',
    name: 'Estrella Fina Árabe',
    categories: ['estrellas', 'minimalistas'],
    tags: ['delicada', 'sutil'],
    aliases: ['estrella chica'],
    comboEligible: true,
  },
  {
    id: 'aes-sparkle-plus',
    symbol: '⊹',
    name: 'Brillo Cruce Elevado',
    categories: ['brillos', 'minimalistas'],
    tags: ['brillo', 'magia', 'cruz'],
    aliases: ['brillito', 'plus sparkle'],
    comboEligible: true,
  },
  {
    id: 'aes-sparkle-pair',
    symbol: '✨',
    name: 'Destellos Mágicos',
    categories: ['brillos', 'estrellas'],
    tags: ['magia', 'brillante', 'oro'],
    aliases: ['chispas', 'destellos dorados', 'sparkles'],
    featured: true,
    comboEligible: true,
  },
  {
    id: 'aes-star-glitter',
    symbol: '✩',
    name: 'Estrella Contorno Suave',
    categories: ['estrellas'],
    tags: ['redondeada', 'sueños'],
    aliases: ['estrella suave'],
    comboEligible: true,
  },
  {
    id: 'aes-star-shadow',
    symbol: '✰',
    name: 'Estrella con Sombra',
    categories: ['estrellas'],
    tags: ['sombra', 'efecto'],
    aliases: ['estrella sombra'],
    comboEligible: true,
  },
  {
    id: 'aes-diamond-small',
    symbol: '⋄',
    name: 'Diamante Sutil',
    categories: ['brillos', 'minimalistas'],
    tags: ['geométrico', 'puro'],
    aliases: ['diamante chico'],
    comboEligible: true,
  },

  // ── Lunas & Cielo (Celestial) ──
  {
    id: 'aes-moon-crescent-left',
    symbol: '☾',
    name: 'Luna Creciente Izquierda',
    categories: ['lunas', 'minimalistas', 'naturaleza'],
    tags: ['noche', 'cielo', 'celestial', 'nocturno'],
    aliases: ['luna', 'moon', 'luna creciente', 'media luna'],
    featured: true,
    comboEligible: true,
  },
  {
    id: 'aes-moon-crescent-right',
    symbol: '☽',
    name: 'Luna Creciente Derecha',
    categories: ['lunas', 'minimalistas', 'naturaleza'],
    tags: ['noche', 'cielo', 'celestial'],
    aliases: ['luna menguante', 'luna derecha'],
    featured: true,
    comboEligible: true,
  },
  {
    id: 'aes-moon-emoji',
    symbol: '🌙',
    name: 'Luna Dorada',
    categories: ['lunas'],
    tags: ['cielo', 'dorada', 'dormir'],
    aliases: ['luna emoji', 'crescent moon'],
    comboEligible: true,
  },
  {
    id: 'aes-sun-outline',
    symbol: '☼',
    name: 'Sol Radiante Contorno',
    categories: ['lunas', 'naturaleza'],
    tags: ['dia', 'día', 'luz', 'calor', 'verano'],
    aliases: ['sol', 'sun', 'sol blanco'],
    comboEligible: true,
  },
  {
    id: 'aes-sun-solid',
    symbol: '☀',
    name: 'Sol Sólido Negro',
    categories: ['lunas', 'naturaleza'],
    tags: ['luz', 'clima'],
    aliases: ['sol negro'],
    comboEligible: true,
  },
  {
    id: 'aes-cloud',
    symbol: '☁',
    name: 'Nube Algodón',
    categories: ['lunas', 'naturaleza', 'cute'],
    tags: ['cielo', 'aire', 'suave', 'lluvia'],
    aliases: ['nube', 'cloud'],
    comboEligible: true,
  },
  {
    id: 'aes-cloud-small',
    symbol: '☁︎',
    name: 'Nube Aesthetic Texto',
    categories: ['lunas', 'naturaleza', 'minimalistas'],
    tags: ['sutil', 'cielo aesthetic'],
    aliases: ['nube texto'],
    comboEligible: true,
  },
  {
    id: 'aes-lightning',
    symbol: '⚡',
    name: 'Rayo Eléctrico',
    categories: ['lunas', 'naturaleza'],
    tags: ['energia', 'energía', 'poder', 'tormenta'],
    aliases: ['rayo', 'trueno', 'lightning'],
    comboEligible: true,
  },
  {
    id: 'aes-comet',
    symbol: '☄',
    name: 'Cometa Cosmico',
    categories: ['lunas', 'naturaleza'],
    tags: ['espacio', 'galaxia'],
    aliases: ['cometa', 'estrella fugaz'],
    comboEligible: true,
  },
  {
    id: 'aes-saturn',
    symbol: '🪐',
    name: 'Planeta Saturno',
    categories: ['lunas', 'naturaleza'],
    tags: ['planeta', 'espacio', 'anillos'],
    aliases: ['planeta', 'saturno', 'galaxia'],
    comboEligible: true,
  },

  // ── Lazos & Coquette ──
  {
    id: 'aes-bow-tibetan',
    symbol: '୨୧',
    name: 'Lazo Coquette Tibetano',
    categories: ['lazos', 'coquette', 'cute'],
    tags: ['lazo', 'coquette', 'moño', 'cinta', 'femenino', 'princesa'],
    aliases: ['lazo', 'coquette', 'mono', 'moño', 'bow', 'ribbon'],
    featured: true,
    comboEligible: true,
  },
  {
    id: 'aes-bow-special',
    symbol: '𐙚',
    name: 'Lazo Coquette Estilizado',
    categories: ['lazos', 'coquette', 'cute'],
    tags: ['coquette chic', 'cinta', 'lazo aesthetic'],
    aliases: ['lazo nuevo', 'lazo coquette chic'],
    featured: true,
    comboEligible: true,
  },
  {
    id: 'aes-bow-ribbon-emoji',
    symbol: '🎀',
    name: 'Cinta Rosada Coquette',
    categories: ['lazos', 'coquette', 'cute'],
    tags: ['rosa', 'regalo', 'moda', 'ballet'],
    aliases: ['cinta rosa', 'lazo rosa'],
    comboEligible: true,
  },
  {
    id: 'aes-bow-korean-heart',
    symbol: 'ᰔ',
    name: 'Corazón Lazo Lepcha',
    categories: ['lazos', 'corazones', 'coquette', 'cute'],
    tags: ['corazon lazo', 'lepcha', 'minimalista'],
    aliases: ['corazon lepcha', 'lazo tierno'],
    comboEligible: true,
  },
  {
    id: 'aes-bow-small',
    symbol: '⑅',
    name: 'Moño Tierno Mini',
    categories: ['lazos', 'coquette', 'minimalistas'],
    tags: ['delicado', 'caja'],
    aliases: ['mono chico', 'moño mini'],
    comboEligible: true,
  },
  {
    id: 'aes-bow-curved-chic',
    symbol: '𝜗𝜚',
    name: 'Lazos Gemelos Cursivos',
    categories: ['lazos', 'coquette'],
    tags: ['par de lazos', 'elegante'],
    aliases: ['doble lazo', 'lazos cursivos'],
    comboEligible: true,
  },
  {
    id: 'aes-coquette-spark-loop',
    symbol: '𓍢ִ໋',
    name: 'Espiral Mágica Coquette',
    categories: ['coquette', 'brillos'],
    tags: ['espiral', 'hada', 'magico'],
    aliases: ['bucle magico', 'espiral coquette'],
    comboEligible: true,
  },
  {
    id: 'aes-coquette-butterfly-knot',
    symbol: '౨ৎ',
    name: 'Nudo Mariposa Coquette',
    categories: ['lazos', 'coquette', 'cute'],
    tags: ['mariposa', 'cinta', 'suave'],
    aliases: ['mariposa coquette', 'nudo mariposa'],
    featured: true,
    comboEligible: true,
  },
  {
    id: 'aes-swan',
    symbol: '🦢',
    name: 'Cisne Elegante',
    categories: ['coquette', 'naturaleza'],
    tags: ['elegancia', 'blanco', 'ballet'],
    aliases: ['cisne', 'swan'],
    comboEligible: true,
  },
  {
    id: 'aes-ballet',
    symbol: '🩰',
    name: 'Zapatillas de Ballet',
    categories: ['coquette'],
    tags: ['ballet', 'danza', 'rosa'],
    aliases: ['zapatillas ballet', 'puntillas'],
    comboEligible: true,
  },

  // ── Flores & Naturaleza ──
  {
    id: 'aes-flower-cherry',
    symbol: '✿',
    name: 'Flor de Cerezo Contorno Negro',
    categories: ['flores', 'naturaleza', 'cute'],
    tags: ['cerezo', 'primavera', 'suave', 'japon'],
    aliases: ['flor', 'flower', 'cerezo', 'sakura'],
    featured: true,
    comboEligible: true,
  },
  {
    id: 'aes-flower-white',
    symbol: '❀',
    name: 'Flor Blanca Ocho Pétalos',
    categories: ['flores', 'naturaleza', 'coquette'],
    tags: ['delicada', 'elegante'],
    aliases: ['flor blanca', 'margarita'],
    featured: true,
    comboEligible: true,
  },
  {
    id: 'aes-flower-blossom',
    symbol: '❁',
    name: 'Flor Abierta Radiante',
    categories: ['flores', 'naturaleza'],
    tags: ['primavera', 'jardin'],
    aliases: ['flor grande', 'blossom'],
    comboEligible: true,
  },
  {
    id: 'aes-flower-stem',
    symbol: '⚘',
    name: 'Flor con Tallo',
    categories: ['flores', 'naturaleza', 'minimalistas'],
    tags: ['tallo', 'rosa', 'tulipan'],
    aliases: ['flor con tallo', 'tulipan'],
    comboEligible: true,
  },
  {
    id: 'aes-flower-pink',
    symbol: '🌸',
    name: 'Flor de Sakura Rosa',
    categories: ['flores', 'cute'],
    tags: ['sakura', 'rosa', 'primavera'],
    aliases: ['sakura', 'flor rosa'],
    comboEligible: true,
  },
  {
    id: 'aes-clover',
    symbol: '☘',
    name: 'Trébol de Tres Hojas',
    categories: ['naturaleza', 'minimalistas'],
    tags: ['suerte', 'verde', 'planta'],
    aliases: ['trebol', 'trébol', 'shamrock'],
    comboEligible: true,
  },
  {
    id: 'aes-herb',
    symbol: '🌿',
    name: 'Rama de Hojas',
    categories: ['naturaleza'],
    tags: ['verde', 'botanica', 'paz'],
    aliases: ['rama', 'hojas', 'hierba'],
    comboEligible: true,
  },
  {
    id: 'aes-butterfly',
    symbol: '🦋',
    name: 'Mariposa Azul',
    categories: ['naturaleza', 'cute', 'coquette'],
    tags: ['vuelo', 'azul', 'transformacion', 'libre'],
    aliases: ['mariposa', 'butterfly'],
    featured: true,
    comboEligible: true,
  },
  {
    id: 'aes-seedling',
    symbol: '🌱',
    name: 'Brote de Planta',
    categories: ['naturaleza'],
    tags: ['crecimiento', 'brote', 'verde'],
    aliases: ['planta', 'brote'],
    comboEligible: true,
  },

  // ── Flechas (Arrows) ──
  {
    id: 'aes-arrow-right',
    symbol: '→',
    name: 'Flecha Derecha Fina',
    categories: ['flechas', 'minimalistas'],
    tags: ['direccion', 'dirección', 'siguiente', 'enlace'],
    aliases: ['flecha', 'arrow', 'flecha derecha'],
    featured: true,
    comboEligible: true,
  },
  {
    id: 'aes-arrow-left',
    symbol: '←',
    name: 'Flecha Izquierda Fina',
    categories: ['flechas', 'minimalistas'],
    tags: ['atras', 'atrás', 'volver'],
    aliases: ['flecha izquierda'],
    comboEligible: true,
  },
  {
    id: 'aes-arrow-heavy',
    symbol: '➔',
    name: 'Flecha Gruesa Indicadora',
    categories: ['flechas'],
    tags: ['guia', 'guía', 'destacar'],
    aliases: ['flecha gruesa'],
    comboEligible: true,
  },
  {
    id: 'aes-arrow-bold',
    symbol: '➜',
    name: 'Flecha Curva Sólida',
    categories: ['flechas'],
    tags: ['marcador', 'bio'],
    aliases: ['flecha solida'],
    comboEligible: true,
  },
  {
    id: 'aes-arrow-triangle',
    symbol: '➤',
    name: 'Flecha Triangular',
    categories: ['flechas'],
    tags: ['puntero', 'moderno'],
    aliases: ['triangulo flecha', 'play flecha'],
    comboEligible: true,
  },
  {
    id: 'aes-arrow-dashed-right',
    symbol: '⇢',
    name: 'Flecha Punteada',
    categories: ['flechas', 'minimalistas'],
    tags: ['puntos', 'delicada'],
    aliases: ['flecha punteada'],
    comboEligible: true,
  },
  {
    id: 'aes-arrow-curved-corner',
    symbol: '↳',
    name: 'Flecha Esquina Descendente',
    categories: ['flechas', 'minimalistas'],
    tags: ['lista', 'jerarquia', 'subtema'],
    aliases: ['flecha lista', 'flecha subitem'],
    comboEligible: true,
  },

  // ── Separadores & Líneas ──
  {
    id: 'aes-sep-bullet',
    symbol: '•',
    name: 'Punto Viñeta Sólido',
    categories: ['separadores', 'minimalistas'],
    tags: ['lista', 'separador', 'bio', 'discreto'],
    aliases: ['punto', 'viñeta', 'bullet', 'separador punto'],
    comboEligible: true,
  },
  {
    id: 'aes-sep-dash-em',
    symbol: '─',
    name: 'Línea Continua Fina',
    categories: ['separadores', 'minimalistas'],
    tags: ['linea', 'divisor', 'horizontal'],
    aliases: ['linea', 'raya', 'separador linea'],
    featured: true,
    comboEligible: true,
  },
  {
    id: 'aes-sep-dash-thick',
    symbol: '━',
    name: 'Línea Gruesa Fuerte',
    categories: ['separadores'],
    tags: ['barra', 'divisor'],
    aliases: ['linea gruesa'],
    comboEligible: true,
  },
  {
    id: 'aes-sep-vert-pipe',
    symbol: '│',
    name: 'Barra Vertical Fina',
    categories: ['separadores', 'minimalistas'],
    tags: ['vertical', 'columna', 'bio'],
    aliases: ['barra vertical', 'separador vertical', 'pipe'],
    comboEligible: true,
  },
  {
    id: 'aes-sep-dots-line',
    symbol: '┊',
    name: 'Barra Vertical Punteada',
    categories: ['separadores', 'minimalistas'],
    tags: ['punteado', 'delicado'],
    aliases: ['barra punteada'],
    comboEligible: true,
  },
  {
    id: 'aes-sep-middle-dot',
    symbol: '·',
    name: 'Punto Medio Sutil',
    categories: ['separadores', 'minimalistas'],
    tags: ['espaciador', 'aesthetic limpio'],
    aliases: ['punto medio', 'dot'],
    featured: true,
    comboEligible: true,
  },

  // ── Marcos & Bordes (Brackets & Frames) ──
  {
    id: 'aes-frame-white-bracket',
    symbol: '『',
    name: 'Marco Esquina Superior Izquierda',
    categories: ['marcos'],
    tags: ['nombre', 'enmarcar', 'japones'],
    aliases: ['marco', 'corchete blanco', 'marco esquina'],
    featured: true,
    comboEligible: true,
  },
  {
    id: 'aes-frame-white-bracket-r',
    symbol: '』',
    name: 'Marco Esquina Inferior Derecha',
    categories: ['marcos'],
    tags: ['nombre', 'cerrar'],
    aliases: ['marco derecho', 'cierre marco'],
    featured: true,
    comboEligible: true,
  },
  {
    id: 'aes-frame-lenticular-l',
    symbol: '【',
    name: 'Marco Lenticular Izquierdo',
    categories: ['marcos'],
    tags: ['bloque', 'destacado'],
    aliases: ['corchete negro', 'marco lente'],
    comboEligible: true,
  },
  {
    id: 'aes-frame-lenticular-r',
    symbol: '】',
    name: 'Marco Lenticular Derecho',
    categories: ['marcos'],
    tags: ['cierre', 'bloque'],
    aliases: ['corchete negro derecho'],
    comboEligible: true,
  },
  {
    id: 'aes-frame-round-l',
    symbol: '꒰',
    name: 'Marco Curvo Tierno Izquierdo',
    categories: ['marcos', 'cute', 'coquette'],
    tags: ['abrazo', 'curva', 'tierno'],
    aliases: ['parentesis tierno', 'marco cute'],
    featured: true,
    comboEligible: true,
  },
  {
    id: 'aes-frame-round-r',
    symbol: '꒱',
    name: 'Marco Curvo Tierno Derecho',
    categories: ['marcos', 'cute', 'coquette'],
    tags: ['cierre tierno', 'cute'],
    aliases: ['parentesis tierno derecho'],
    featured: true,
    comboEligible: true,
  },
  {
    id: 'aes-frame-angle-l',
    symbol: '《',
    name: 'Marco Doble Ángulo Izquierdo',
    categories: ['marcos'],
    tags: ['clasico', 'libro'],
    aliases: ['angulo doble', 'chevron'],
    comboEligible: true,
  },
  {
    id: 'aes-frame-angle-r',
    symbol: '》',
    name: 'Marco Doble Ángulo Derecho',
    categories: ['marcos'],
    tags: ['cierre angulo'],
    aliases: ['angulo doble derecho'],
    comboEligible: true,
  },
  {
    id: 'aes-frame-wing-l',
    symbol: '༺',
    name: 'Ala Decorativa Izquierda',
    categories: ['marcos', 'cute'],
    tags: ['ala', 'decoracion', 'nick'],
    aliases: ['ala izquierda', 'borde ala'],
    comboEligible: true,
  },
  {
    id: 'aes-frame-wing-r',
    symbol: '༻',
    name: 'Ala Decorativa Derecha',
    categories: ['marcos', 'cute'],
    tags: ['ala', 'cierre ala'],
    aliases: ['ala derecha'],
    comboEligible: true,
  },

  // ── Música & Audio ──
  {
    id: 'aes-music-double',
    symbol: '♫',
    name: 'Doble Nota Musical',
    categories: ['musica', 'cute'],
    tags: ['cancion', 'sonido', 'melodia', 'ritmo'],
    aliases: ['musica', 'música', 'nota musical', 'music'],
    featured: true,
    comboEligible: true,
  },
  {
    id: 'aes-music-single',
    symbol: '♪',
    name: 'Nota Musical Solitaria',
    categories: ['musica', 'minimalistas'],
    tags: ['acustico', 'cancion'],
    aliases: ['nota', 'musica simple'],
    featured: true,
    comboEligible: true,
  },
  {
    id: 'aes-music-notes',
    symbol: '♬',
    name: 'Notas Musicales Conectadas',
    categories: ['musica'],
    tags: ['armonia', 'melodia'],
    aliases: ['notas dobles'],
    comboEligible: true,
  },
  {
    id: 'aes-music-headphones',
    symbol: '🎧',
    name: 'Auriculares / Headphones',
    categories: ['musica'],
    tags: ['audifonos', 'cancion', 'spotify'],
    aliases: ['auriculares', 'audifonos', 'headphones'],
    comboEligible: true,
  },

  // ── Cute & Kaomoji Faces ──
  {
    id: 'aes-cute-cat',
    symbol: 'ฅ^•ﻌ•^ฅ',
    name: 'Gatito con Patitas',
    categories: ['cute'],
    tags: ['gato', 'michi', 'felino', 'kawaii', 'mascota'],
    aliases: ['gato', 'michi', 'cat', 'gatito'],
    featured: true,
    comboEligible: false,
  },
  {
    id: 'aes-cute-love-face',
    symbol: '(｡♥‿♥｡)',
    name: 'Carita Enamorada con Corazón',
    categories: ['cute', 'corazones'],
    tags: ['amor', 'enamorado', 'kawaii'],
    aliases: ['enamorado', 'carita amor'],
    featured: true,
    comboEligible: false,
  },
  {
    id: 'aes-cute-sparkle-thumbs',
    symbol: 'ദ്ദി(˵ •̀ ᴗ - ˵ )',
    name: 'Guiño de Aprobación',
    categories: ['cute'],
    tags: ['pulgar arriba', 'animo', 'guiño'],
    aliases: ['aprobacion', 'guiño', 'like'],
    featured: true,
    comboEligible: false,
  },
  {
    id: 'aes-cute-bunny',
    symbol: '₍ᐢ. .ᐢ₎',
    name: 'Conejito Tierno',
    categories: ['cute', 'coquette'],
    tags: ['conejo', 'tierno', 'orejitas'],
    aliases: ['conejo', 'bunny'],
    comboEligible: false,
  },
  {
    id: 'aes-cute-hug',
    symbol: '(づ｡◕‿‿◕｡)づ',
    name: 'Abrazo Afectuoso',
    categories: ['cute'],
    tags: ['abrazo', 'cariño'],
    aliases: ['abrazo', 'hug'],
    comboEligible: false,
  },
  {
    id: 'aes-cute-angel',
    symbol: 'ପ(๑•ᴗ•๑)ଓ',
    name: 'Angelito de la Guarda',
    categories: ['cute', 'coquette'],
    tags: ['angel', 'alas', 'inocente'],
    aliases: ['angel', 'angelito'],
    comboEligible: false,
  },
];

// ── Ready-Made Combinations (Categorized by Use Case) ──
export const AESTHETIC_READY_COMBOS: AestheticReadyCombo[] = [
  // Para nombres
  { id: 'combo-nom-1', combo: '୨୧ nombre ୨୧', name: 'Lazos Coquette', useCase: 'nombres', tags: ['coquette', 'lazo', 'chica', 'tierno'] },
  { id: 'combo-nom-2', combo: '♡ nombre ♡', name: 'Marco Corazones Suaves', useCase: 'nombres', tags: ['corazon', 'amor', 'romantico'] },
  { id: 'combo-nom-3', combo: '✦ nombre ✦', name: 'Destellos Mágicos', useCase: 'nombres', tags: ['brillo', 'estrella', 'sparkle'] },
  { id: 'combo-nom-4', combo: '☾ nombre ☽', name: 'Lunas Gemelas', useCase: 'nombres', tags: ['luna', 'noche', 'celestial'] },
  { id: 'combo-nom-5', combo: '『 nombre 』', name: 'Enmarcado Oriental', useCase: 'nombres', tags: ['marco', 'elegante', 'japones'] },
  { id: 'combo-nom-6', combo: '꒰ nombre ꒱', name: 'Abrazo Curvo Cute', useCase: 'nombres', tags: ['cute', 'tierno', 'suave'] },
  { id: 'combo-nom-7', combo: '𐙚 nombre 𐙚', name: 'Lazos Chic', useCase: 'nombres', tags: ['coquette', 'moda', 'cinta'] },
  { id: 'combo-nom-8', combo: '⋆｡°✩ nombre ✩°｡⋆', name: 'Nube Estrellada', useCase: 'nombres', tags: ['cielo', 'estrellas', 'sueño'] },
  { id: 'combo-nom-9', combo: '《 ☬ nombre ☬ 》', name: 'Emblema Místico', useCase: 'nombres', tags: ['mistico', 'misterio', 'gamer'] },
  { id: 'combo-nom-10', combo: '✿ nombre ✿', name: 'Flor de Primavera', useCase: 'nombres', tags: ['flor', 'primavera', 'botanico'] },
  { id: 'combo-nom-11', combo: '🦋 ✦ nombre ✦ 🦋', name: 'Mariposas Radiantes', useCase: 'nombres', tags: ['mariposa', 'brillo', 'azul'] },
  { id: 'combo-nom-12', combo: '౨ৎ nombre ౨ৎ', name: 'Mariposa Coquette', useCase: 'nombres', tags: ['coquette', 'mariposa', 'delicado'] },

  // Para bios
  { id: 'combo-bio-1', combo: '✦ sobre mí', name: 'Viñeta Destello', useCase: 'bios', tags: ['bio', 'perfil', 'introduccion'] },
  { id: 'combo-bio-2', combo: '⋆｡°✩ sobre mí ✩°｡⋆', name: 'Cabecera de Perfil', useCase: 'bios', tags: ['bio', 'cabecera', 'instagram'] },
  { id: 'combo-bio-3', combo: '──── ✦ ────', name: 'Divisor Estelar', useCase: 'bios', tags: ['separador', 'linea', 'bloque'] },
  { id: 'combo-bio-4', combo: '✿ música ✿ viajes ✿ café', name: 'Intereses Florales', useCase: 'bios', tags: ['intereses', 'gustos', 'flor'] },
  { id: 'combo-bio-5', combo: '☾ sueños ✦ metas ☾', name: 'Aspiraciones Nocturnas', useCase: 'bios', tags: ['metas', 'frase', 'inspiracion'] },
  { id: 'combo-bio-6', combo: '♡ libre ♡ soñadora ♡', name: 'Línea de Actitud', useCase: 'bios', tags: ['actitud', 'personalidad', 'corazon'] },
  { id: 'combo-bio-7', combo: '♫ playlist favorita ♪', name: 'Sección Musical', useCase: 'bios', tags: ['musica', 'spotify', 'canciones'] },
  { id: 'combo-bio-8', combo: '✦ inicio → planes → final ✦', name: 'Línea de Ruta', useCase: 'bios', tags: ['flecha', 'trayectoria', 'guia'] },

  // Para separar texto
  { id: 'combo-sep-1', combo: '• • •', name: 'Puntos Suspensivos Sutiles', useCase: 'separadores', tags: ['minimalista', 'discreto', 'puntos'] },
  { id: 'combo-sep-2', combo: '⋆ ⋆ ⋆', name: 'Trío Estelar', useCase: 'separadores', tags: ['estrellas', 'separador'] },
  { id: 'combo-sep-3', combo: '──── ♡ ────', name: 'Línea con Corazón', useCase: 'separadores', tags: ['linea', 'romantico', 'romántico'] },
  { id: 'combo-sep-4', combo: '✦ ─── ✦', name: 'Línea con Destellos', useCase: 'separadores', tags: ['brillo', 'linea'] },
  { id: 'combo-sep-5', combo: '♡ ─── ♡', name: 'Línea Corazones Gemelos', useCase: 'separadores', tags: ['corazon', 'divisor'] },
  { id: 'combo-sep-6', combo: '─── ⋆⋅☆⋅⋆ ───', name: 'Constelación de Separación', useCase: 'separadores', tags: ['complejo', 'elegante'] },
  { id: 'combo-sep-7', combo: '· ˚₊‧ ✦ ‧₊˚ ·', name: 'Destello Centrado Puro', useCase: 'separadores', tags: ['minimalista', 'polvo estelar'] },
  { id: 'combo-sep-8', combo: '⟡ ── ⟡ ── ⟡', name: 'Diamantes en Cadena', useCase: 'separadores', tags: ['diamantes', 'joyas', 'fino'] },
  { id: 'combo-sep-9', combo: '⋆｡°✩', name: 'Firmita Cósmica', useCase: 'separadores', tags: ['firma', 'cierre'] },

  // Minimalistas y coquette
  { id: 'combo-mini-1', combo: '· ♡ ·', name: 'Corazón Minimalista', useCase: 'minimalistas-coquette', tags: ['minimalista', 'puntos', 'corazon'] },
  { id: 'combo-mini-2', combo: '˚ ✦ ˚', name: 'Destello Solitario', useCase: 'minimalistas-coquette', tags: ['brillo', 'minimalista'] },
  { id: 'combo-mini-3', combo: '⋆ ☾ ⋆', name: 'Noche Mínima', useCase: 'minimalistas-coquette', tags: ['luna', 'estrellas'] },
  { id: 'combo-mini-4', combo: '୨୧ ⋆ ♡ ⋆ ୨୧', name: 'Lazos y Corazón Suave', useCase: 'minimalistas-coquette', tags: ['coquette', 'lazo', 'amor'] },
  { id: 'combo-mini-5', combo: '𐙚 ♡ 𐙚', name: 'Chic Corazón', useCase: 'minimalistas-coquette', tags: ['coquette chic', 'tierno'] },
  { id: 'combo-mini-6', combo: '౨ৎ Princesa ౨ৎ', name: 'Princesa Coquette', useCase: 'minimalistas-coquette', tags: ['princesa', 'coquette', 'corona'] },
  { id: 'combo-mini-7', combo: '𓆩♡𓆪 Ángel Caído 𓆩♡𓆪', name: 'Alas Dark Corazón', useCase: 'minimalistas-coquette', tags: ['dark aesthetic', 'alas'] },
  { id: 'combo-mini-8', combo: '✨ 𝒱𝒾𝒷𝑒𝓈 ✨', name: 'Vibras Mágicas', useCase: 'minimalistas-coquette', tags: ['vibes', 'aesthetic', 'magia'] },
  { id: 'combo-mini-9', combo: '✧˚. ༘⋆ 𝒟𝓇𝑒𝒶𝓂𝓈 ✧˚. ༘⋆', name: 'Sueños Cósmicos Cursiva', useCase: 'minimalistas-coquette', tags: ['dreams', 'sueños', 'cursiva'] },
];

/**
 * Normalizes a Spanish string by converting to lowercase and stripping accents.
 * Does NOT modify stored symbols or copied values.
 */
export function normalizeSpanishSearch(text: string): string {
  return text
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .trim();
}

/**
 * Search aesthetic symbols using category filtering and normalized semantic tags/aliases.
 */
export function searchAestheticSymbols(
  query: string,
  category: AestheticCategory
): AestheticSymbol[] {
  const clean = normalizeSpanishSearch(query);

  return AESTHETIC_SYMBOLS.filter(item => {
    const matchesCategory = category === 'todos' || item.categories.includes(category);
    if (!matchesCategory) return false;
    if (!clean) return true;

    const symbolMatch = item.symbol.toLowerCase().includes(clean);
    const nameMatch = normalizeSpanishSearch(item.name).includes(clean);
    const tagMatch = item.tags.some(t => normalizeSpanishSearch(t).includes(clean));
    const aliasMatch = item.aliases.some(a => normalizeSpanishSearch(a).includes(clean));

    return symbolMatch || nameMatch || tagMatch || aliasMatch;
  });
}
