export type BonitoCategory =
  | 'todos'
  | 'corazones'
  | 'estrellas'
  | 'flores'
  | 'lunas'
  | 'flechas'
  | 'coronas'
  | 'musica'
  | 'separadores'
  | 'marcos'
  | 'utiles'
  | 'especiales'
  | 'numeros';

export interface BonitoSymbol {
  id: string;
  symbol: string;
  name: string;
  categories: BonitoCategory[];
  tags: string[];
  aliases: string[];
  featured?: boolean;
}

export interface BonitoReadyCombo {
  id: string;
  combo: string;
  name: string;
  useCase: 'nombres' | 'bios' | 'separadores';
  tags: string[];
}

export const BONITO_CATEGORIES: { id: BonitoCategory; label: string; icon: string }[] = [
  { id: 'todos', label: 'Todos', icon: '✨' },
  { id: 'corazones', label: 'Corazones', icon: '♡' },
  { id: 'estrellas', label: 'Estrellas', icon: '★' },
  { id: 'flores', label: 'Flores', icon: '✿' },
  { id: 'lunas', label: 'Lunas', icon: '☾' },
  { id: 'flechas', label: 'Flechas', icon: '➜' },
  { id: 'coronas', label: 'Coronas', icon: '♔' },
  { id: 'musica', label: 'Música', icon: '♪' },
  { id: 'separadores', label: 'Separadores', icon: '━' },
  { id: 'marcos', label: 'Marcos', icon: '『 』' },
  { id: 'utiles', label: 'Útiles', icon: '✓' },
  { id: 'especiales', label: 'Especiales', icon: '∞' },
  { id: 'numeros', label: 'Números', icon: '①' },
];

export const BONITO_SYMBOLS: BonitoSymbol[] = [
  // ── Corazones (Hearts) ──
  {
    id: 'bon-heart-outline',
    symbol: '♡',
    name: 'Corazón Contorno Blanco',
    categories: ['corazones'],
    tags: ['amor', 'romantico', 'romántico', 'tierno'],
    aliases: ['corazon', 'corazón', 'heart', 'love', 'blanco'],
    featured: true,
  },
  {
    id: 'bon-heart-solid',
    symbol: '♥',
    name: 'Corazón Sólido Negro',
    categories: ['corazones'],
    tags: ['amor', 'clasico', 'clásico', 'pareja'],
    aliases: ['corazon negro', 'corazón negro', 'black heart'],
    featured: true,
  },
  {
    id: 'bon-heart-red',
    symbol: '❤',
    name: 'Corazón Rojo',
    categories: ['corazones'],
    tags: ['rojo', 'amor', 'pasion'],
    aliases: ['corazon rojo', 'red heart'],
    featured: true,
  },
  {
    id: 'bon-heart-rot',
    symbol: '❥',
    name: 'Corazón Rotado Elegante',
    categories: ['corazones'],
    tags: ['adorno', 'delicado', 'estilo'],
    aliases: ['corazon curvo', 'corazon decorativo'],
  },
  {
    id: 'bon-heart-exclam',
    symbol: '❣',
    name: 'Corazón Exclamación',
    categories: ['corazones'],
    tags: ['exclamacion', 'enfasis'],
    aliases: ['corazon signo'],
  },
  {
    id: 'bon-heart-curved',
    symbol: 'ღ',
    name: 'Corazón Georgiano',
    categories: ['corazones'],
    tags: ['romantico', 'antiguo', 'femenino'],
    aliases: ['corazon suave'],
    featured: true,
  },
  {
    id: 'bon-heart-sparkle',
    symbol: '💖',
    name: 'Corazón Brillante',
    categories: ['corazones'],
    tags: ['brillo', 'destello', 'rosa'],
    aliases: ['sparkle heart'],
    featured: true,
  },
  {
    id: 'bon-heart-double',
    symbol: '💕',
    name: 'Dos Corazones',
    categories: ['corazones'],
    tags: ['amistad', 'enamorados'],
    aliases: ['dos corazones', 'corazones rosas'],
  },
  {
    id: 'bon-heart-growing',
    symbol: '💗',
    name: 'Corazón Creciente',
    categories: ['corazones'],
    tags: ['latido', 'vibrante'],
    aliases: ['corazon latiendo'],
  },
  {
    id: 'bon-heart-arrow',
    symbol: '💘',
    name: 'Corazón con Flecha',
    categories: ['corazones'],
    tags: ['cupido', 'flechazo'],
    aliases: ['cupido'],
  },
  {
    id: 'bon-heart-ribbon',
    symbol: '💝',
    name: 'Corazón con Lazo',
    categories: ['corazones'],
    tags: ['regalo', 'lazo'],
    aliases: ['corazon regalo'],
  },
  {
    id: 'bon-heart-white',
    symbol: '🤍',
    name: 'Corazón Blanco Puro',
    categories: ['corazones'],
    tags: ['blanco', 'paz', 'limpio'],
    aliases: ['corazon blanco'],
  },
  {
    id: 'bon-heart-ivy',
    symbol: '❦',
    name: 'Corazón Floral Hiedra',
    categories: ['corazones', 'flores'],
    tags: ['vintage', 'botanico'],
    aliases: ['hiedra'],
  },
  {
    id: 'bon-heart-cherub',
    symbol: 'დ',
    name: 'Corazón Cherub',
    categories: ['corazones'],
    tags: ['tierno', 'angelical'],
    aliases: ['doni'],
  },
  {
    id: 'bon-heart-cute',
    symbol: 'ෆ',
    name: 'Corazón Tierno Malayalam',
    categories: ['corazones'],
    tags: ['korean', 'tierno'],
    aliases: ['fa'],
    featured: true,
  },

  // ── Estrellas & Brillos (Stars) ──
  {
    id: 'bon-star-solid',
    symbol: '★',
    name: 'Estrella Sólida Negra',
    categories: ['estrellas'],
    tags: ['noche', 'cielo', 'brillante'],
    aliases: ['estrella', 'star', 'estrella negra'],
    featured: true,
  },
  {
    id: 'bon-star-outline',
    symbol: '☆',
    name: 'Estrella Contorno Blanca',
    categories: ['estrellas'],
    tags: ['vacia', 'blanca', 'linea'],
    aliases: ['estrella blanca', 'estrella vacia'],
    featured: true,
  },
  {
    id: 'bon-sparkle-4-solid',
    symbol: '✦',
    name: 'Destello Cuatro Puntas Sólido',
    categories: ['estrellas'],
    tags: ['brillo', 'magia', 'destello'],
    aliases: ['brillo', 'destello', 'sparkle'],
    featured: true,
  },
  {
    id: 'bon-sparkle-4-out',
    symbol: '✧',
    name: 'Destello Cuatro Puntas Contorno',
    categories: ['estrellas'],
    tags: ['brillo sutil', 'magia'],
    aliases: ['destello blanco'],
    featured: true,
  },
  {
    id: 'bon-star-circled',
    symbol: '✪',
    name: 'Estrella Encerrada en Círculo',
    categories: ['estrellas'],
    tags: ['emblema', 'insignia'],
    aliases: ['estrella circulo'],
  },
  {
    id: 'bon-star-small',
    symbol: '⋆',
    name: 'Estrella Pequeña Sutil',
    categories: ['estrellas'],
    tags: ['polvo', 'cosmico'],
    aliases: ['estrellita', 'starlet'],
  },
  {
    id: 'bon-star-diamond',
    symbol: '⟡',
    name: 'Diamante con Destello',
    categories: ['estrellas'],
    tags: ['joya', 'cristal'],
    aliases: ['diamante estrella'],
  },
  {
    id: 'bon-star-glitter',
    symbol: '✩',
    name: 'Estrella Suave',
    categories: ['estrellas'],
    tags: ['sueño', 'redondeada'],
    aliases: ['estrella suave'],
  },
  {
    id: 'bon-star-shadow',
    symbol: '✰',
    name: 'Estrella con Sombra',
    categories: ['estrellas'],
    tags: ['sombra', 'efecto'],
    aliases: ['estrella sombra'],
  },
  {
    id: 'bon-star-pinwheel',
    symbol: '✫',
    name: 'Estrella Abierta Molinete',
    categories: ['estrellas'],
    tags: ['molinete', 'cinco puntas'],
    aliases: ['estrella molino'],
  },
  {
    id: 'bon-star-sparkle-emoji',
    symbol: '✨',
    name: 'Destellos Brillantes',
    categories: ['estrellas'],
    tags: ['magia', 'dorado', 'chispas'],
    aliases: ['chispas', 'sparkles'],
    featured: true,
  },
  {
    id: 'bon-star-8point',
    symbol: '✴',
    name: 'Estrella de Ocho Puntas',
    categories: ['estrellas'],
    tags: ['ocho puntas', 'destello'],
    aliases: ['estrella 8 puntas'],
  },

  // ── Flores & Naturaleza (Flowers) ──
  {
    id: 'bon-flower-cherry',
    symbol: '✿',
    name: 'Flor de Cerezo Contorno',
    categories: ['flores'],
    tags: ['sakura', 'primavera', 'suave'],
    aliases: ['flor', 'flower', 'sakura'],
    featured: true,
  },
  {
    id: 'bon-flower-white',
    symbol: '❀',
    name: 'Flor Blanca Ocho Pétalos',
    categories: ['flores'],
    tags: ['margarita', 'delicada'],
    aliases: ['flor blanca', 'margarita'],
    featured: true,
  },
  {
    id: 'bon-flower-radiant',
    symbol: '❁',
    name: 'Flor Radiante Grande',
    categories: ['flores'],
    tags: ['jardin', 'primavera'],
    aliases: ['blossom'],
  },
  {
    id: 'bon-flower-stem',
    symbol: '⚘',
    name: 'Flor con Tallo',
    categories: ['flores'],
    tags: ['tulipan', 'rosa'],
    aliases: ['tulipan', 'flor tallo'],
  },
  {
    id: 'bon-flower-petal',
    symbol: '✾',
    name: 'Flor Seis Pétalos',
    categories: ['flores'],
    tags: ['jardin', 'petalos'],
    aliases: ['flor seis petalos'],
  },
  {
    id: 'bon-flower-heavy',
    symbol: '❃',
    name: 'Flor Gruesa',
    categories: ['flores'],
    tags: ['rellena', 'decorativa'],
    aliases: ['flor gruesa'],
  },
  {
    id: 'bon-flower-sakura',
    symbol: '🌸',
    name: 'Flor de Sakura Rosa',
    categories: ['flores'],
    tags: ['rosa', 'cerezo', 'japon'],
    aliases: ['flor rosa', 'cerezo rosa'],
    featured: true,
  },
  {
    id: 'bon-flower-hibiscus',
    symbol: '🌺',
    name: 'Flor de Hibisco',
    categories: ['flores'],
    tags: ['tropical', 'rojo'],
    aliases: ['hibisco', 'flor roja'],
  },
  {
    id: 'bon-flower-tulip',
    symbol: '🌷',
    name: 'Tulipán',
    categories: ['flores'],
    tags: ['tulipan', 'holanda'],
    aliases: ['tulipan flor'],
  },
  {
    id: 'bon-clover',
    symbol: '☘',
    name: 'Trébol de Tres Hojas',
    categories: ['flores'],
    tags: ['suerte', 'verde', 'planta'],
    aliases: ['trebol', 'trébol'],
  },

  // ── Lunas & Cielo (Moons & Sky) ──
  {
    id: 'bon-moon-crescent-left',
    symbol: '☾',
    name: 'Luna Creciente Izquierda',
    categories: ['lunas'],
    tags: ['noche', 'cielo', 'celestial'],
    aliases: ['luna', 'moon', 'luna creciente'],
    featured: true,
  },
  {
    id: 'bon-moon-crescent-right',
    symbol: '☽',
    name: 'Luna Menguante Derecha',
    categories: ['lunas'],
    tags: ['noche', 'cielo'],
    aliases: ['luna menguante'],
    featured: true,
  },
  {
    id: 'bon-moon-emoji',
    symbol: '🌙',
    name: 'Luna Dorada',
    categories: ['lunas'],
    tags: ['dorado', 'noche'],
    aliases: ['luna emoji'],
  },
  {
    id: 'bon-sun-outline',
    symbol: '☼',
    name: 'Sol Radiante Contorno',
    categories: ['lunas'],
    tags: ['sol', 'luz', 'dia'],
    aliases: ['sol', 'sun'],
  },
  {
    id: 'bon-sun-solid',
    symbol: '☀',
    name: 'Sol Negro Sólido',
    categories: ['lunas'],
    tags: ['dia', 'verano'],
    aliases: ['sol negro'],
  },
  {
    id: 'bon-cloud',
    symbol: '☁',
    name: 'Nube Algodón',
    categories: ['lunas'],
    tags: ['cielo', 'suave'],
    aliases: ['nube', 'cloud'],
  },
  {
    id: 'bon-cloud-small',
    symbol: '☁︎',
    name: 'Nube Texto Sutil',
    categories: ['lunas'],
    tags: ['cielo aesthetic'],
    aliases: ['nube sutil'],
  },
  {
    id: 'bon-lightning',
    symbol: '⚡',
    name: 'Rayo Eléctrico',
    categories: ['lunas'],
    tags: ['energia', 'tormenta'],
    aliases: ['rayo', 'trueno'],
  },
  {
    id: 'bon-planet',
    symbol: '🪐',
    name: 'Planeta Saturno',
    categories: ['lunas'],
    tags: ['espacio', 'galaxia'],
    aliases: ['saturno', 'planeta'],
  },

  // ── Flechas (Arrows) ──
  {
    id: 'bon-arrow-right',
    symbol: '→',
    name: 'Flecha Derecha Fina',
    categories: ['flechas'],
    tags: ['direccion', 'siguiente'],
    aliases: ['flecha', 'arrow', 'flecha derecha'],
    featured: true,
  },
  {
    id: 'bon-arrow-left',
    symbol: '←',
    name: 'Flecha Izquierda Fina',
    categories: ['flechas'],
    tags: ['atras', 'volver'],
    aliases: ['flecha izquierda'],
  },
  {
    id: 'bon-arrow-up',
    symbol: '↑',
    name: 'Flecha Arriba',
    categories: ['flechas'],
    tags: ['subir', 'arriba'],
    aliases: ['flecha arriba'],
  },
  {
    id: 'bon-arrow-down',
    symbol: '↓',
    name: 'Flecha Abajo',
    categories: ['flechas'],
    tags: ['bajar', 'abajo'],
    aliases: ['flecha abajo'],
  },
  {
    id: 'bon-arrow-heavy',
    symbol: '➜',
    name: 'Flecha Gruesa Indicadora',
    categories: ['flechas'],
    tags: ['marcador', 'bio'],
    aliases: ['flecha gruesa'],
    featured: true,
  },
  {
    id: 'bon-arrow-triangle',
    symbol: '➤',
    name: 'Flecha Triangular',
    categories: ['flechas'],
    tags: ['puntero', 'play'],
    aliases: ['flecha triangulo'],
    featured: true,
  },
  {
    id: 'bon-arrow-feather',
    symbol: '➳',
    name: 'Flecha con Plumas',
    categories: ['flechas'],
    tags: ['pluma', 'arco'],
    aliases: ['flecha pluma', 'arco y flecha'],
  },
  {
    id: 'bon-arrow-feather-alt',
    symbol: '➵',
    name: 'Flecha Clásica con Plumas',
    categories: ['flechas'],
    tags: ['indigena', 'tiro'],
    aliases: ['flecha arco'],
  },
  {
    id: 'bon-arrow-dashed',
    symbol: '⇢',
    name: 'Flecha Punteada',
    categories: ['flechas'],
    tags: ['puntos', 'delicada'],
    aliases: ['flecha puntos'],
  },
  {
    id: 'bon-arrow-corner',
    symbol: '↳',
    name: 'Flecha Esquina Subtema',
    categories: ['flechas'],
    tags: ['lista', 'jerarquia'],
    aliases: ['flecha subitem'],
  },

  // ── Coronas & Realeza (Crowns) ──
  {
    id: 'bon-crown-white-king',
    symbol: '♔',
    name: 'Rey Blanco Ajedrez',
    categories: ['coronas'],
    tags: ['rey', 'ajedrez', 'corona'],
    aliases: ['corona rey', 'rey blanco', 'corona'],
    featured: true,
  },
  {
    id: 'bon-crown-white-queen',
    symbol: '♕',
    name: 'Reina Blanca Ajedrez',
    categories: ['coronas'],
    tags: ['reina', 'corona', 'ajedrez'],
    aliases: ['corona reina', 'reina blanca'],
    featured: true,
  },
  {
    id: 'bon-crown-black-king',
    symbol: '♚',
    name: 'Rey Negro Ajedrez',
    categories: ['coronas'],
    tags: ['rey negro', 'poder'],
    aliases: ['rey negro'],
    featured: true,
  },
  {
    id: 'bon-crown-black-queen',
    symbol: '♛',
    name: 'Reina Negra Ajedrez',
    categories: ['coronas'],
    tags: ['reina negra', 'realeza'],
    aliases: ['reina negra'],
    featured: true,
  },
  {
    id: 'bon-crown-gold-emoji',
    symbol: '👑',
    name: 'Corona Dorada Real',
    categories: ['coronas'],
    tags: ['oro', 'realeza', 'victoria', 'vip'],
    aliases: ['corona oro', 'corona emoji', 'crown'],
    featured: true,
  },
  {
    id: 'bon-fleur-de-lis',
    symbol: '⚜',
    name: 'Flor de Lis Heráldica',
    categories: ['coronas'],
    tags: ['realeza', 'heraldica', 'francia'],
    aliases: ['flor de lis', 'heraldica'],
  },
  {
    id: 'bon-clan-insane',
    symbol: '亗',
    name: 'Sello de Clan Asiático',
    categories: ['coronas'],
    tags: ['clan', 'gamer', 'nick'],
    aliases: ['corona clan', 'clan chino'],
  },

  // ── Música (Music) ──
  {
    id: 'bon-music-single',
    symbol: '♪',
    name: 'Nota Musical Solitaria',
    categories: ['musica'],
    tags: ['cancion', 'sonido', 'acustico'],
    aliases: ['musica', 'música', 'nota musical', 'music'],
    featured: true,
  },
  {
    id: 'bon-music-double',
    symbol: '♫',
    name: 'Doble Nota Musical',
    categories: ['musica'],
    tags: ['cancion', 'melodia', 'ritmo'],
    aliases: ['doble nota', 'musica par'],
    featured: true,
  },
  {
    id: 'bon-music-connected',
    symbol: '♬',
    name: 'Notas Musicales Conectadas',
    categories: ['musica'],
    tags: ['armonia', 'partitura'],
    aliases: ['notas conectadas'],
  },
  {
    id: 'bon-music-quarter',
    symbol: '♩',
    name: 'Nota Negra Musical',
    categories: ['musica'],
    tags: ['ritmo', 'tempo'],
    aliases: ['nota negra'],
  },
  {
    id: 'bon-music-flat',
    symbol: '♭',
    name: 'Bemol Musical',
    categories: ['musica'],
    tags: ['bemol', 'tono'],
    aliases: ['bemol'],
  },
  {
    id: 'bon-music-sharp',
    symbol: '♯',
    name: 'Sostenido Musical',
    categories: ['musica'],
    tags: ['sostenido', 'acorde'],
    aliases: ['sostenido'],
  },
  {
    id: 'bon-music-headphones',
    symbol: '🎧',
    name: 'Auriculares de Música',
    categories: ['musica'],
    tags: ['audifonos', 'spotify'],
    aliases: ['auriculares', 'audifonos'],
  },

  // ── Separadores (Separators) ──
  {
    id: 'bon-sep-dash-thick',
    symbol: '━',
    name: 'Línea Continua Gruesa',
    categories: ['separadores'],
    tags: ['linea', 'divisor'],
    aliases: ['linea gruesa', 'separador grueso'],
    featured: true,
  },
  {
    id: 'bon-sep-dash-thin',
    symbol: '─',
    name: 'Línea Continua Fina',
    categories: ['separadores'],
    tags: ['linea', 'divisor fino'],
    aliases: ['linea fina'],
  },
  {
    id: 'bon-sep-bullet',
    symbol: '•',
    name: 'Punto Viñeta',
    categories: ['separadores'],
    tags: ['punto', 'viñeta', 'bio'],
    aliases: ['punto viñeta', 'bullet'],
  },
  {
    id: 'bon-sep-vert-pipe',
    symbol: '│',
    name: 'Barra Vertical',
    categories: ['separadores'],
    tags: ['vertical', 'columna'],
    aliases: ['pipe', 'barra vertical'],
  },
  {
    id: 'bon-sep-dots-vert',
    symbol: '┊',
    name: 'Barra Punteada Vertical',
    categories: ['separadores'],
    tags: ['punteado', 'delicado'],
    aliases: ['puntos verticales'],
  },
  {
    id: 'bon-sep-dot-mid',
    symbol: '·',
    name: 'Punto Medio Sutil',
    categories: ['separadores'],
    tags: ['espaciador', 'discreto'],
    aliases: ['punto medio'],
  },

  // ── Marcos (Frames & Brackets) ──
  {
    id: 'bon-frame-white-l',
    symbol: '『',
    name: 'Marco Esquina Blanco Izquierdo',
    categories: ['marcos'],
    tags: ['nombre', 'enmarcar'],
    aliases: ['marco izquierdo', 'corchete blanco'],
    featured: true,
  },
  {
    id: 'bon-frame-white-r',
    symbol: '』',
    name: 'Marco Esquina Blanco Derecho',
    categories: ['marcos'],
    tags: ['nombre', 'cierre'],
    aliases: ['marco derecho'],
    featured: true,
  },
  {
    id: 'bon-frame-corner-l',
    symbol: '「',
    name: 'Marco Esquina Simple Izquierdo',
    categories: ['marcos'],
    tags: ['japones', 'cita'],
    aliases: ['marco simple'],
  },
  {
    id: 'bon-frame-corner-r',
    symbol: '」',
    name: 'Marco Esquina Simple Derecho',
    categories: ['marcos'],
    tags: ['cierre simple'],
    aliases: ['cierre esquina'],
  },
  {
    id: 'bon-frame-lenticular-l',
    symbol: '【',
    name: 'Marco Lenticular Izquierdo',
    categories: ['marcos'],
    tags: ['bloque', 'destacado'],
    aliases: ['corchete negro'],
    featured: true,
  },
  {
    id: 'bon-frame-lenticular-r',
    symbol: '】',
    name: 'Marco Lenticular Derecho',
    categories: ['marcos'],
    tags: ['cierre bloque'],
    aliases: ['corchete negro derecho'],
    featured: true,
  },
  {
    id: 'bon-frame-cute-l',
    symbol: '꒰',
    name: 'Marco Curvo Tierno Izquierdo',
    categories: ['marcos'],
    tags: ['cute', 'curva', 'abrazo'],
    aliases: ['parentesis tierno'],
  },
  {
    id: 'bon-frame-cute-r',
    symbol: '꒱',
    name: 'Marco Curvo Tierno Derecho',
    categories: ['marcos'],
    tags: ['cute', 'cierre tierno'],
    aliases: ['parentesis tierno derecho'],
  },
  {
    id: 'bon-frame-wings-l',
    symbol: '༺',
    name: 'Ala Decorativa Izquierda',
    categories: ['marcos'],
    tags: ['ala', 'nick', 'gamer'],
    aliases: ['ala izquierda'],
  },
  {
    id: 'bon-frame-wings-r',
    symbol: '༻',
    name: 'Ala Decorativa Derecha',
    categories: ['marcos'],
    tags: ['ala', 'cierre ala'],
    aliases: ['ala derecha'],
  },
  {
    id: 'bon-frame-ornament-l',
    symbol: '꧁',
    name: 'Brote Ornamental Izquierdo',
    categories: ['marcos'],
    tags: ['ornamento', 'floritura'],
    aliases: ['floritura izquierda'],
  },
  {
    id: 'bon-frame-ornament-r',
    symbol: '꧂',
    name: 'Brote Ornamental Derecho',
    categories: ['marcos'],
    tags: ['floritura derecha'],
    aliases: ['floritura derecha'],
  },

  // ── Útiles & Marcas (Useful Marks) ──
  {
    id: 'bon-mark-check',
    symbol: '✓',
    name: 'Marca de Verificación Fina',
    categories: ['utiles'],
    tags: ['correcto', 'check', 'aprobado', 'tarea'],
    aliases: ['check', 'palomita', 'visto', 'marca'],
    featured: true,
  },
  {
    id: 'bon-mark-check-bold',
    symbol: '✔',
    name: 'Marca de Verificación Gruesa',
    categories: ['utiles'],
    tags: ['correcto', 'check negro', 'afirmativo'],
    aliases: ['check grueso', 'palomita negra'],
    featured: true,
  },
  {
    id: 'bon-mark-cross',
    symbol: '✗',
    name: 'Cruz de Rechazo Fina',
    categories: ['utiles'],
    tags: ['tache', 'error', 'cancelar'],
    aliases: ['tache', 'cruz', 'equis'],
  },
  {
    id: 'bon-mark-cross-bold',
    symbol: '✘',
    name: 'Cruz de Rechazo Gruesa',
    categories: ['utiles'],
    tags: ['error grave', 'cancelado'],
    aliases: ['tache grueso'],
  },
  {
    id: 'bon-mark-x',
    symbol: '✕',
    name: 'Multiplicación / Equis Sencilla',
    categories: ['utiles'],
    tags: ['cerrar', 'equis'],
    aliases: ['equis simple'],
  },
  {
    id: 'bon-mark-mail',
    symbol: '✉',
    name: 'Sobre de Correo',
    categories: ['utiles'],
    tags: ['email', 'mensaje', 'contacto'],
    aliases: ['correo', 'carta', 'email'],
  },
  {
    id: 'bon-mark-phone',
    symbol: '☎',
    name: 'Teléfono Clásico',
    categories: ['utiles'],
    tags: ['llamada', 'contacto'],
    aliases: ['telefono', 'teléfono'],
  },
  {
    id: 'bon-mark-plane',
    symbol: '✈',
    name: 'Avión de Viaje',
    categories: ['utiles'],
    tags: ['viaje', 'turismo', 'vuelo'],
    aliases: ['avion', 'avión'],
  },
  {
    id: 'bon-mark-pencil',
    symbol: '✎',
    name: 'Lápiz de Escribir',
    categories: ['utiles'],
    tags: ['redaccion', 'nota'],
    aliases: ['lapiz', 'lápiz'],
  },
  {
    id: 'bon-mark-copyright',
    symbol: '©',
    name: 'Signo de Copyright',
    categories: ['utiles'],
    tags: ['derechos', 'legal', 'autor'],
    aliases: ['copyright'],
  },
  {
    id: 'bon-mark-registered',
    symbol: '®',
    name: 'Marca Registrada',
    categories: ['utiles'],
    tags: ['registro', 'marca'],
    aliases: ['marca registrada', 'registered'],
  },
  {
    id: 'bon-mark-trademark',
    symbol: '™',
    name: 'Trade Mark',
    categories: ['utiles'],
    tags: ['comercio', 'marca'],
    aliases: ['trademark'],
  },

  // ── Especiales (Special Symbols) ──
  {
    id: 'bon-spec-infinity',
    symbol: '∞',
    name: 'Signo de Infinito',
    categories: ['especiales'],
    tags: ['eterno', 'sin fin', 'matematicas'],
    aliases: ['infinito', 'infinity'],
    featured: true,
  },
  {
    id: 'bon-spec-yinyang',
    symbol: '☯',
    name: 'Yin Yang',
    categories: ['especiales'],
    tags: ['equilibrio', 'tao', 'armonia'],
    aliases: ['yin yang', 'yinyang'],
    featured: true,
  },
  {
    id: 'bon-spec-peace',
    symbol: '☮',
    name: 'Símbolo de la Paz',
    categories: ['especiales'],
    tags: ['paz', 'armonia', 'tranquilidad'],
    aliases: ['paz', 'peace'],
    featured: true,
  },
  {
    id: 'bon-spec-swords',
    symbol: '⚔',
    name: 'Espadas Cruzadas',
    categories: ['especiales'],
    tags: ['batalla', 'gamer', 'lucha'],
    aliases: ['espadas', 'combate'],
    featured: true,
  },
  {
    id: 'bon-spec-skull',
    symbol: '☠',
    name: 'Calavera con Huesos',
    categories: ['especiales'],
    tags: ['peligro', 'gamer', 'veneno'],
    aliases: ['calavera', 'muerte'],
  },
  {
    id: 'bon-spec-crosshairs',
    symbol: '⌖',
    name: 'Mira de Precisión',
    categories: ['especiales'],
    tags: ['punteria', 'mira', 'disparo'],
    aliases: ['mira gamer', 'crosshair'],
  },
  {
    id: 'bon-spec-biohazard',
    symbol: '☣',
    name: 'Riesgo Biológico',
    categories: ['especiales'],
    tags: ['toxico', 'radioactivo', 'gamer'],
    aliases: ['biohazard', 'toxico'],
  },
  {
    id: 'bon-spec-radiation',
    symbol: '☢',
    name: 'Radiación',
    categories: ['especiales'],
    tags: ['nuclear', 'energia'],
    aliases: ['radiacion', 'nuclear'],
  },
  {
    id: 'bon-spec-ankh',
    symbol: '☥',
    name: 'Cruz Anj de la Vida',
    categories: ['especiales'],
    tags: ['egipto', 'vida', 'eterna'],
    aliases: ['ankh', 'cruz egipcia'],
  },
  {
    id: 'bon-spec-venus',
    symbol: '♀',
    name: 'Símbolo de Venus / Mujer',
    categories: ['especiales'],
    tags: ['femenino', 'venus', 'mujer'],
    aliases: ['femenino', 'mujer'],
  },
  {
    id: 'bon-spec-mars',
    symbol: '♂',
    name: 'Símbolo de Marte / Hombre',
    categories: ['especiales'],
    tags: ['masculino', 'marte', 'hombre'],
    aliases: ['masculino', 'hombre'],
  },

  // ── Números Decorados (Decorated Numbers) ──
  { id: 'bon-num-1', symbol: '①', name: 'Número Uno en Círculo', categories: ['numeros'], tags: ['uno', 'primer'], aliases: ['1', 'uno'] },
  { id: 'bon-num-2', symbol: '②', name: 'Número Dos en Círculo', categories: ['numeros'], tags: ['dos', 'segundo'], aliases: ['2', 'dos'] },
  { id: 'bon-num-3', symbol: '③', name: 'Número Tres en Círculo', categories: ['numeros'], tags: ['tres', 'tercer'], aliases: ['3', 'tres'] },
  { id: 'bon-num-4', symbol: '④', name: 'Número Cuatro en Círculo', categories: ['numeros'], tags: ['cuatro'], aliases: ['4', 'cuatro'] },
  { id: 'bon-num-5', symbol: '⑤', name: 'Número Cinco en Círculo', categories: ['numeros'], tags: ['cinco'], aliases: ['5', 'cinco'] },
  { id: 'bon-num-6', symbol: '⑥', name: 'Número Seis en Círculo', categories: ['numeros'], tags: ['seis'], aliases: ['6', 'seis'] },
  { id: 'bon-num-7', symbol: '⑦', name: 'Número Siete en Círculo', categories: ['numeros'], tags: ['siete'], aliases: ['7', 'siete'] },
  { id: 'bon-num-8', symbol: '⑧', name: 'Número Ocho en Círculo', categories: ['numeros'], tags: ['ocho'], aliases: ['8', 'ocho'] },
  { id: 'bon-num-9', symbol: '⑨', name: 'Número Nueve en Círculo', categories: ['numeros'], tags: ['nueve'], aliases: ['9', 'nueve'] },
  { id: 'bon-num-10', symbol: '⑩', name: 'Número Diez en Círculo', categories: ['numeros'], tags: ['diez'], aliases: ['10', 'diez'] },
  { id: 'bon-num-b-1', symbol: '❶', name: 'Número Uno Negro', categories: ['numeros'], tags: ['uno negro'], aliases: ['1 negro'] },
  { id: 'bon-num-b-2', symbol: '❷', name: 'Número Dos Negro', categories: ['numeros'], tags: ['dos negro'], aliases: ['2 negro'] },
  { id: 'bon-num-b-3', symbol: '❸', name: 'Número Tres Negro', categories: ['numeros'], tags: ['tres negro'], aliases: ['3 negro'] },
  { id: 'bon-num-b-4', symbol: '❹', name: 'Número Cuatro Negro', categories: ['numeros'], tags: ['cuatro negro'], aliases: ['4 negro'] },
  { id: 'bon-num-b-5', symbol: '❺', name: 'Número Cinco Negro', categories: ['numeros'], tags: ['cinco negro'], aliases: ['5 negro'] },
];

export const BONITO_READY_COMBOS: BonitoReadyCombo[] = [
  // Para nombres
  { id: 'combo-bon-1', combo: '♡ nombre ♡', name: 'Marco de Corazones', useCase: 'nombres', tags: ['corazon', 'amor', 'tierno'] },
  { id: 'combo-bon-2', combo: '✦ nombre ✦', name: 'Marco de Destellos', useCase: 'nombres', tags: ['brillo', 'magia', 'estrella'] },
  { id: 'combo-bon-3', combo: '★ nombre ★', name: 'Estrellas Clásicas', useCase: 'nombres', tags: ['estrella', 'destacado'] },
  { id: 'combo-bon-4', combo: '✿ nombre ✿', name: 'Flores de Primavera', useCase: 'nombres', tags: ['flor', 'primavera', 'suave'] },
  { id: 'combo-bon-5', combo: '☾ nombre ☽', name: 'Lunas Gemelas', useCase: 'nombres', tags: ['luna', 'noche', 'celestial'] },
  { id: 'combo-bon-6', combo: '『 nombre 』', name: 'Enmarcado Oriental', useCase: 'nombres', tags: ['marco', 'corchete', 'elegante'] },
  { id: 'combo-bon-7', combo: '♔ nombre ♔', name: 'Corona Real', useCase: 'nombres', tags: ['corona', 'realeza', 'rey'] },
  { id: 'combo-bon-8', combo: '꒰ nombre ꒱', name: 'Abrazo Curvo Cute', useCase: 'nombres', tags: ['cute', 'tierno'] },
  { id: 'combo-bon-9', combo: '♬ nombre ♬', name: 'Notas Musicales', useCase: 'nombres', tags: ['musica', 'cancion', 'melodia'] },
  { id: 'combo-bon-10', combo: '☾ ⋆ nombre ⋆ ☽', name: 'Noche Estrellada', useCase: 'nombres', tags: ['luna', 'estrella', 'cielo'] },

  // Para bios
  { id: 'combo-bon-bio-1', combo: '♡ sobre mí', name: 'Sección Personal', useCase: 'bios', tags: ['bio', 'perfil', 'introduccion'] },
  { id: 'combo-bon-bio-2', combo: '♪ música', name: 'Interés Musical', useCase: 'bios', tags: ['musica', 'cancion', 'bio'] },
  { id: 'combo-bon-bio-3', combo: '✿ naturaleza', name: 'Interés Natural', useCase: 'bios', tags: ['flor', 'naturaleza', 'planta'] },
  { id: 'combo-bon-bio-4', combo: '✦ proyectos', name: 'Sección de Proyectos', useCase: 'bios', tags: ['proyectos', 'planes', 'metas'] },
  { id: 'combo-bon-bio-5', combo: '──── ✦ ────', name: 'Divisor Estelar', useCase: 'bios', tags: ['separador', 'linea', 'bloque'] },
  { id: 'combo-bon-bio-6', combo: '★ objetivos → logros', name: 'Ruta de Metas', useCase: 'bios', tags: ['flecha', 'trayectoria'] },
  { id: 'combo-bon-bio-7', combo: '☾ sueños ✦ metas', name: 'Inspiración Nocturna', useCase: 'bios', tags: ['metas', 'frase'] },

  // Para separar texto
  { id: 'combo-bon-sep-1', combo: '• • •', name: 'Puntos Suspensivos', useCase: 'separadores', tags: ['puntos', 'minimalista'] },
  { id: 'combo-bon-sep-2', combo: '⋆ ⋆ ⋆', name: 'Trío de Estrellas', useCase: 'separadores', tags: ['estrellas', 'divisor'] },
  { id: 'combo-bon-sep-3', combo: '━ ♡ ━', name: 'Línea con Corazón', useCase: 'separadores', tags: ['corazon', 'linea', 'romantico'] },
  { id: 'combo-bon-sep-4', combo: '✦ ─── ✦', name: 'Línea con Destellos', useCase: 'separadores', tags: ['brillo', 'linea'] },
  { id: 'combo-bon-sep-5', combo: '♡ · ♡ · ♡', name: 'Corazones Espaciados', useCase: 'separadores', tags: ['corazones', 'puntos'] },
  { id: 'combo-bon-sep-6', combo: '─── ⋆⋅☆⋅⋆ ───', name: 'Constelación de Separación', useCase: 'separadores', tags: ['complejo', 'elegante'] },
  { id: 'combo-bon-sep-7', combo: '──── ✦ ────', name: 'Línea Estelar Centrada', useCase: 'separadores', tags: ['estrellas', 'divisor'] },
];

/**
 * Normalizes a Spanish query (lowercase, strips accents, trims).
 */
export function normalizeSpanishSearch(text: string): string {
  return text
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .trim();
}

/**
 * Search bonitos symbols with category filtering and semantic aliases.
 */
export function searchBonitosSymbols(
  query: string,
  category: BonitoCategory
): BonitoSymbol[] {
  const clean = normalizeSpanishSearch(query);

  return BONITO_SYMBOLS.filter(item => {
    const matchesCategory = category === 'todos' || item.categories.includes(category);
    if (!matchesCategory) return false;
    if (!clean) return true;

    const symbolMatch = item.symbol.toLowerCase().includes(clean);
    const nameMatch = normalizeSpanishSearch(item.name).includes(clean);
    const tagMatch = item.tags.some(t => normalizeSpanishSearch(t).includes(clean));
    const aliasMatch = item.aliases.some(a => normalizeSpanishSearch(a).includes(clean));

    return symbolMatch || nameMatch || tagMatch || aliasMatch;
  });
}
