export type EspecialCategory =
  | 'todos'
  | 'matematicas'
  | 'flechas'
  | 'monedas'
  | 'marcas'
  | 'puntuacion'
  | 'formas'
  | 'tecnicos'
  | 'griegos'
  | 'superindices'
  | 'subindices'
  | 'musica'
  | 'juegos'
  | 'otros';

export interface EspecialConfusable {
  symbol: string;
  name: string;
  distinction: string;
}

export interface EspecialSymbol {
  id: string;
  symbol: string;
  nameEs: string;
  nameUnicode: string;
  codePoint: string;
  categories: EspecialCategory[];
  tags: string[];
  aliases: string[];
  confusableWith?: EspecialConfusable;
  keyboardTip?: string;
  featured?: boolean;
}

export const ESPECIAL_CATEGORIES: { id: EspecialCategory; label: string; icon: string }[] = [
  { id: 'todos', label: 'Todos', icon: '⚡' },
  { id: 'matematicas', label: 'Matemáticas', icon: '∑' },
  { id: 'flechas', label: 'Flechas', icon: '→' },
  { id: 'monedas', label: 'Monedas', icon: '€' },
  { id: 'marcas', label: 'Marcas y Signos', icon: '©' },
  { id: 'puntuacion', label: 'Puntuación', icon: '§' },
  { id: 'formas', label: 'Formas', icon: '▲' },
  { id: 'tecnicos', label: 'Técnicos', icon: '⌘' },
  { id: 'griegos', label: 'Griegos', icon: 'π' },
  { id: 'superindices', label: 'Superíndices', icon: '¹²³' },
  { id: 'subindices', label: 'Subíndices', icon: '₁₂₃' },
  { id: 'musica', label: 'Música', icon: '♪' },
  { id: 'juegos', label: 'Juegos', icon: '♠' },
  { id: 'otros', label: 'Otros', icon: '✓' },
];

export const ESPECIAL_SYMBOLS: EspecialSymbol[] = [
  // ════════════════════════════════════════════════════════════════
  // ── MATEMÁTICAS (Mathematical Operators & Science) ──
  // ════════════════════════════════════════════════════════════════
  {
    id: 'esp-mat-neq',
    symbol: '≠',
    nameEs: 'Diferente de / No igual',
    nameUnicode: 'NOT EQUAL TO',
    codePoint: 'U+2260',
    categories: ['matematicas'],
    tags: ['diferente', 'desigualdad', 'comparacion', 'algebra'],
    aliases: ['diferente', 'no igual', 'distinto', 'desigual', 'not equal', 'no es igual'],
    confusableWith: {
      symbol: '=',
      name: 'Signo igual',
      distinction: '≠ expresa desigualdad estricta, mientras que = indica equivalencia.',
    },
    featured: true,
  },
  {
    id: 'esp-mat-inf',
    symbol: '∞',
    nameEs: 'Infinito',
    nameUnicode: 'INFINITY',
    codePoint: 'U+221E',
    categories: ['matematicas'],
    tags: ['infinito', 'lemniscata', 'calculo', 'limite'],
    aliases: ['infinito', 'lemniscata', 'sin fin', 'infinity', 'limite al infinito'],
    featured: true,
  },
  {
    id: 'esp-mat-sqrt',
    symbol: '√',
    nameEs: 'Raíz cuadrada',
    nameUnicode: 'SQUARE ROOT',
    codePoint: 'U+221A',
    categories: ['matematicas'],
    tags: ['raiz', 'radical', 'algebra'],
    aliases: ['raiz', 'raíz', 'raiz cuadrada', 'radical', 'square root'],
    featured: true,
  },
  {
    id: 'esp-mat-cbrt',
    symbol: '∛',
    nameEs: 'Raíz cúbica',
    nameUnicode: 'CUBE ROOT',
    codePoint: 'U+221B',
    categories: ['matematicas'],
    tags: ['raiz cubica', 'radical'],
    aliases: ['raiz cubica', 'raíz cúbica', 'cube root'],
  },
  {
    id: 'esp-mat-fourthrt',
    symbol: '∜',
    nameEs: 'Raíz cuarta',
    nameUnicode: 'FOURTH ROOT',
    codePoint: 'U+221C',
    categories: ['matematicas'],
    tags: ['raiz cuarta', 'radical'],
    aliases: ['raiz cuarta', 'raíz cuarta', 'fourth root'],
  },
  {
    id: 'esp-mat-plusminus',
    symbol: '±',
    nameEs: 'Más o menos / Más menos',
    nameUnicode: 'PLUS-MINUS SIGN',
    codePoint: 'U+00B1',
    categories: ['matematicas'],
    tags: ['tolerancia', 'error', 'positivo negativo'],
    aliases: ['mas o menos', 'más o menos', 'mas menos', 'plus minus', 'tolerancia'],
    featured: true,
  },
  {
    id: 'esp-mat-minusplus',
    symbol: '∓',
    nameEs: 'Menos o más',
    nameUnicode: 'MINUS-OR-PLUS SIGN',
    codePoint: 'U+2213',
    categories: ['matematicas'],
    tags: ['negativo positivo', 'algebra'],
    aliases: ['menos o mas', 'menos o más', 'minus plus'],
  },
  {
    id: 'esp-mat-times',
    symbol: '×',
    nameEs: 'Signo de multiplicación',
    nameUnicode: 'MULTIPLICATION SIGN',
    codePoint: 'U+00D7',
    categories: ['matematicas'],
    tags: ['multiplicar', 'por', 'producto', 'dimensiones'],
    aliases: ['por', 'multiplicacion', 'multiplicación', 'times', 'signo de multiplicar', 'producto'],
    confusableWith: {
      symbol: 'x',
      name: 'Letra equis latina minúscula',
      distinction: '× es el operador aritmético simétrico (U+00D7), mientras que x es una letra (U+0078).',
    },
    featured: true,
  },
  {
    id: 'esp-mat-divide',
    symbol: '÷',
    nameEs: 'Signo de división / Óbelo',
    nameUnicode: 'DIVISION SIGN',
    codePoint: 'U+00F7',
    categories: ['matematicas'],
    tags: ['dividir', 'cociente', 'obelo'],
    aliases: ['entre', 'division', 'división', 'obelo', 'divide', 'signo de dividir'],
    featured: true,
  },
  {
    id: 'esp-mat-minus',
    symbol: '−',
    nameEs: 'Signo menos matemático',
    nameUnicode: 'MINUS SIGN',
    codePoint: 'U+2212',
    categories: ['matematicas'],
    tags: ['resta', 'negativo', 'sustraccion'],
    aliases: ['menos', 'signo menos', 'resta', 'minus'],
    confusableWith: {
      symbol: '-',
      name: 'Guion-menos del teclado',
      distinction: '− (U+2212) tiene la misma anchura que el signo + para alineación numérica en fórmulas.',
    },
    featured: true,
  },
  {
    id: 'esp-mat-approx',
    symbol: '≈',
    nameEs: 'Aproximadamente igual a',
    nameUnicode: 'ALMOST EQUAL TO',
    codePoint: 'U+2248',
    categories: ['matematicas'],
    tags: ['aproximado', 'estimacion', 'redondeo'],
    aliases: ['aproximadamente', 'casi igual', 'aproximado', 'approx', 'redondeo'],
    featured: true,
  },
  {
    id: 'esp-mat-ident',
    symbol: '≡',
    nameEs: 'Idéntico a / Congruencia',
    nameUnicode: 'IDENTICAL TO',
    codePoint: 'U+2261',
    categories: ['matematicas'],
    tags: ['identidad', 'congruencia', 'modular'],
    aliases: ['identico', 'idéntico', 'congruente', 'triple raya'],
  },
  {
    id: 'esp-mat-lte',
    symbol: '≤',
    nameEs: 'Menor o igual que',
    nameUnicode: 'LESS-THAN OR EQUAL TO',
    codePoint: 'U+2264',
    categories: ['matematicas'],
    tags: ['desigualdad', 'comparacion', 'menor'],
    aliases: ['menor o igual', 'menor igual', 'less than or equal', 'no mayor que'],
    featured: true,
  },
  {
    id: 'esp-mat-gte',
    symbol: '≥',
    nameEs: 'Mayor o igual que',
    nameUnicode: 'GREATER-THAN OR EQUAL TO',
    codePoint: 'U+2265',
    categories: ['matematicas'],
    tags: ['desigualdad', 'comparacion', 'mayor'],
    aliases: ['mayor o igual', 'mayor igual', 'greater than or equal', 'no menor que'],
    featured: true,
  },
  {
    id: 'esp-mat-sum',
    symbol: '∑',
    nameEs: 'Sumatoria / Suma de serie',
    nameUnicode: 'N-ARY SUMMATION',
    codePoint: 'U+2211',
    categories: ['matematicas'],
    tags: ['sumatoria', 'sigma', 'serie'],
    aliases: ['sumatoria', 'suma', 'sigma mayuscula', 'summation'],
    featured: true,
  },
  {
    id: 'esp-mat-prod',
    symbol: '∏',
    nameEs: 'Productoria / Producto de serie',
    nameUnicode: 'N-ARY PRODUCT',
    codePoint: 'U+220F',
    categories: ['matematicas'],
    tags: ['productoria', 'pi', 'serie'],
    aliases: ['productoria', 'producto', 'pi mayuscula', 'product'],
  },
  {
    id: 'esp-mat-integral',
    symbol: '∫',
    nameEs: 'Integral simple',
    nameUnicode: 'INTEGRAL',
    codePoint: 'U+222B',
    categories: ['matematicas'],
    tags: ['calculo', 'integral', 'derivada'],
    aliases: ['integral', 'calculo integral', 'integracion'],
    featured: true,
  },
  {
    id: 'esp-mat-double-int',
    symbol: '∬',
    nameEs: 'Integral doble',
    nameUnicode: 'DOUBLE INTEGRAL',
    codePoint: 'U+222C',
    categories: ['matematicas'],
    tags: ['calculo multivariable', 'area'],
    aliases: ['integral doble', 'doble integral'],
  },
  {
    id: 'esp-mat-triple-int',
    symbol: '∭',
    nameEs: 'Integral triple',
    nameUnicode: 'TRIPLE INTEGRAL',
    codePoint: 'U+222D',
    categories: ['matematicas'],
    tags: ['calculo multivariable', 'volumen'],
    aliases: ['integral triple', 'triple integral'],
  },
  {
    id: 'esp-mat-partial',
    symbol: '∂',
    nameEs: 'Derivada parcial',
    nameUnicode: 'PARTIAL DIFFERENTIAL',
    codePoint: 'U+2202',
    categories: ['matematicas'],
    tags: ['calculo', 'derivada', 'parcial'],
    aliases: ['derivada parcial', 'diferencial parcial', 'del'],
  },
  {
    id: 'esp-mat-nabla',
    symbol: '∇',
    nameEs: 'Nabla / Gradiente',
    nameUnicode: 'NABLA',
    codePoint: 'U+2207',
    categories: ['matematicas'],
    tags: ['vectorial', 'gradiente', 'divergencia', 'rotacional'],
    aliases: ['nabla', 'gradiente', 'vectorial'],
  },
  {
    id: 'esp-mat-in',
    symbol: '∈',
    nameEs: 'Pertenece a',
    nameUnicode: 'ELEMENT OF',
    codePoint: 'U+2208',
    categories: ['matematicas'],
    tags: ['conjuntos', 'pertenencia', 'teoria de conjuntos'],
    aliases: ['pertenece', 'es elemento de', 'element of'],
  },
  {
    id: 'esp-mat-notin',
    symbol: '∉',
    nameEs: 'No pertenece a',
    nameUnicode: 'NOT AN ELEMENT OF',
    codePoint: 'U+2209',
    categories: ['matematicas'],
    tags: ['conjuntos', 'no pertenencia'],
    aliases: ['no pertenece', 'no es elemento de', 'not in'],
  },
  {
    id: 'esp-mat-subset',
    symbol: '⊂',
    nameEs: 'Subconjunto propio de',
    nameUnicode: 'SUBSET OF',
    codePoint: 'U+2282',
    categories: ['matematicas'],
    tags: ['conjuntos', 'subconjunto', 'contenido'],
    aliases: ['subconjunto', 'contenido en', 'subset'],
  },
  {
    id: 'esp-mat-superset',
    symbol: '⊃',
    nameEs: 'Superconjunto de',
    nameUnicode: 'SUPERSET OF',
    codePoint: 'U+2283',
    categories: ['matematicas'],
    tags: ['conjuntos', 'contiene'],
    aliases: ['superconjunto', 'contiene a', 'superset'],
  },
  {
    id: 'esp-mat-subseteq',
    symbol: '⊆',
    nameEs: 'Subconjunto o igual',
    nameUnicode: 'SUBSET OF OR EQUAL TO',
    codePoint: 'U+2286',
    categories: ['matematicas'],
    tags: ['conjuntos', 'subconjunto'],
    aliases: ['subconjunto o igual', 'contenido o igual'],
  },
  {
    id: 'esp-mat-union',
    symbol: '∪',
    nameEs: 'Unión de conjuntos',
    nameUnicode: 'UNION',
    codePoint: 'U+222A',
    categories: ['matematicas'],
    tags: ['conjuntos', 'union'],
    aliases: ['union', 'unión', 'union de conjuntos'],
  },
  {
    id: 'esp-mat-intersect',
    symbol: '∩',
    nameEs: 'Intersección de conjuntos',
    nameUnicode: 'INTERSECTION',
    codePoint: 'U+2229',
    categories: ['matematicas'],
    tags: ['conjuntos', 'interseccion'],
    aliases: ['interseccion', 'intersección', 'interseccion de conjuntos'],
  },
  {
    id: 'esp-mat-forall',
    symbol: '∀',
    nameEs: 'Para todo / Cuantificador universal',
    nameUnicode: 'FOR ALL',
    codePoint: 'U+2200',
    categories: ['matematicas'],
    tags: ['logica', 'cuantificador', 'universal'],
    aliases: ['para todo', 'para cada', 'for all', 'a invertida'],
  },
  {
    id: 'esp-mat-exists',
    symbol: '∃',
    nameEs: 'Existe / Cuantificador existencial',
    nameUnicode: 'THERE EXISTS',
    codePoint: 'U+2203',
    categories: ['matematicas'],
    tags: ['logica', 'existencial'],
    aliases: ['existe', 'existe al menos uno', 'there exists', 'e invertida'],
  },
  {
    id: 'esp-mat-notexists',
    symbol: '∄',
    nameEs: 'No existe',
    nameUnicode: 'THERE DOES NOT EXIST',
    codePoint: 'U+2204',
    categories: ['matematicas'],
    tags: ['logica', 'no existencial'],
    aliases: ['no existe', 'there does not exist'],
  },
  {
    id: 'esp-mat-emptyset',
    symbol: '∅',
    nameEs: 'Conjunto vacío',
    nameUnicode: 'EMPTY SET',
    codePoint: 'U+2205',
    categories: ['matematicas'],
    tags: ['conjunto vacio', 'nulo'],
    aliases: ['vacio', 'vacío', 'conjunto vacio', 'conjunto vacío', 'empty set', 'cero tachado'],
    confusableWith: {
      symbol: 'Ø',
      name: 'Letra O barrada nórdica',
      distinction: '∅ es el símbolo de conjunto vacío (U+2205), mientras que Ø es una letra del alfabeto (U+00D8).',
    },
  },
  {
    id: 'esp-mat-proportional',
    symbol: '∝',
    nameEs: 'Proporcional a',
    nameUnicode: 'PROPORTIONAL TO',
    codePoint: 'U+221D',
    categories: ['matematicas'],
    tags: ['proporcion', 'fisica'],
    aliases: ['proporcional', 'proporcional a', 'variacion'],
  },
  {
    id: 'esp-mat-angle',
    symbol: '∠',
    nameEs: 'Ángulo',
    nameUnicode: 'ANGLE',
    codePoint: 'U+2220',
    categories: ['matematicas'],
    tags: ['geometria', 'trigonometria'],
    aliases: ['angulo', 'ángulo', 'angle'],
  },
  {
    id: 'esp-mat-rightangle',
    symbol: '∟',
    nameEs: 'Ángulo recto',
    nameUnicode: 'RIGHT ANGLE',
    codePoint: 'U+221F',
    categories: ['matematicas'],
    tags: ['geometria', '90 grados'],
    aliases: ['angulo recto', 'ángulo recto', '90 grados'],
  },
  {
    id: 'esp-mat-perpendicular',
    symbol: '⊥',
    nameEs: 'Perpendicular a',
    nameUnicode: 'UP TACK',
    codePoint: 'U+22A5',
    categories: ['matematicas'],
    tags: ['geometria', 'ortogonal'],
    aliases: ['perpendicular', 'ortogonal', 'te invertida'],
  },
  {
    id: 'esp-mat-parallel',
    symbol: '∥',
    nameEs: 'Paralelo a',
    nameUnicode: 'PARALLEL TO',
    codePoint: 'U+2225',
    categories: ['matematicas'],
    tags: ['geometria', 'paralelo'],
    aliases: ['paralelo', 'lineas paralelas'],
  },
  {
    id: 'esp-mat-logical-not',
    symbol: '¬',
    nameEs: 'Negación lógica',
    nameUnicode: 'NOT SIGN',
    codePoint: 'U+00AC',
    categories: ['matematicas'],
    tags: ['logica', 'negacion'],
    aliases: ['negacion', 'negación', 'no logico', 'logical not'],
  },
  {
    id: 'esp-mat-permille',
    symbol: '‰',
    nameEs: 'Por mil / Tanto por mil',
    nameUnicode: 'PER MILLE SIGN',
    codePoint: 'U+2030',
    categories: ['matematicas'],
    tags: ['porcentaje', 'estadistica'],
    aliases: ['por mil', 'tanto por mil', 'per mille'],
  },
  {
    id: 'esp-mat-pertenmille',
    symbol: '‱',
    nameEs: 'Punto base / Por diez mil',
    nameUnicode: 'PER TEN THOUSAND SIGN',
    codePoint: 'U+2031',
    categories: ['matematicas'],
    tags: ['finanzas', 'punto base', 'basis point'],
    aliases: ['punto base', 'por diez mil', 'basis point', 'bp'],
  },

  // ════════════════════════════════════════════════════════════════
  // ── FLECHAS (Arrows & Directions) ──
  // ════════════════════════════════════════════════════════════════
  {
    id: 'esp-arr-right',
    symbol: '→',
    nameEs: 'Flecha hacia la derecha',
    nameUnicode: 'RIGHTWARDS ARROW',
    codePoint: 'U+2192',
    categories: ['flechas'],
    tags: ['derecha', 'direccion', 'siguiente', 'avanzar'],
    aliases: ['flecha derecha', 'derecha', 'flecha hacia la derecha', 'siguiente', 'proximo', 'right arrow'],
    featured: true,
  },
  {
    id: 'esp-arr-left',
    symbol: '←',
    nameEs: 'Flecha hacia la izquierda',
    nameUnicode: 'LEFTWARDS ARROW',
    codePoint: 'U+2190',
    categories: ['flechas'],
    tags: ['izquierda', 'atras', 'anterior'],
    aliases: ['flecha izquierda', 'izquierda', 'retroceder', 'atras', 'left arrow'],
    featured: true,
  },
  {
    id: 'esp-arr-up',
    symbol: '↑',
    nameEs: 'Flecha hacia arriba',
    nameUnicode: 'UPWARDS ARROW',
    codePoint: 'U+2191',
    categories: ['flechas'],
    tags: ['arriba', 'subir', 'norte'],
    aliases: ['flecha arriba', 'arriba', 'subir', 'up arrow'],
    featured: true,
  },
  {
    id: 'esp-arr-down',
    symbol: '↓',
    nameEs: 'Flecha hacia abajo',
    nameUnicode: 'DOWNWARDS ARROW',
    codePoint: 'U+2193',
    categories: ['flechas'],
    tags: ['abajo', 'bajar', 'sur'],
    aliases: ['flecha abajo', 'abajo', 'bajar', 'down arrow'],
    featured: true,
  },
  {
    id: 'esp-arr-lr',
    symbol: '↔',
    nameEs: 'Flecha bidireccional horizontal',
    nameUnicode: 'LEFT RIGHT ARROW',
    codePoint: 'U+2194',
    categories: ['flechas'],
    tags: ['horizontal', 'ambos lados', 'intercambio'],
    aliases: ['flecha doble horizontal', 'bidireccional', 'ambos lados', 'doble sentido'],
    featured: true,
  },
  {
    id: 'esp-arr-ud',
    symbol: '↕',
    nameEs: 'Flecha bidireccional vertical',
    nameUnicode: 'UP DOWN ARROW',
    codePoint: 'U+2195',
    categories: ['flechas'],
    tags: ['vertical', 'subir y bajar'],
    aliases: ['flecha vertical', 'subir y bajar', 'doble sentido vertical'],
  },
  {
    id: 'esp-arr-nw',
    symbol: '↖',
    nameEs: 'Flecha hacia arriba a la izquierda',
    nameUnicode: 'NORTH WEST ARROW',
    codePoint: 'U+2196',
    categories: ['flechas'],
    tags: ['diagonal', 'noroeste'],
    aliases: ['diagonal noroeste', 'arriba izquierda'],
  },
  {
    id: 'esp-arr-ne',
    symbol: '↗',
    nameEs: 'Flecha hacia arriba a la derecha',
    nameUnicode: 'NORTH EAST ARROW',
    codePoint: 'U+2197',
    categories: ['flechas'],
    tags: ['diagonal', 'noreste', 'enlace externo'],
    aliases: ['diagonal noreste', 'arriba derecha', 'enlace externo'],
    featured: true,
  },
  {
    id: 'esp-arr-se',
    symbol: '↘',
    nameEs: 'Flecha hacia abajo a la derecha',
    nameUnicode: 'SOUTH EAST ARROW',
    codePoint: 'U+2198',
    categories: ['flechas'],
    tags: ['diagonal', 'sureste'],
    aliases: ['diagonal sureste', 'abajo derecha'],
  },
  {
    id: 'esp-arr-sw',
    symbol: '↙',
    nameEs: 'Flecha hacia abajo a la izquierda',
    nameUnicode: 'SOUTH WEST ARROW',
    codePoint: 'U+2199',
    categories: ['flechas'],
    tags: ['diagonal', 'suroeste'],
    aliases: ['diagonal suroeste', 'abajo izquierda'],
  },
  {
    id: 'esp-arr-dbl-right',
    symbol: '⇒',
    nameEs: 'Flecha doble derecha / Implicación',
    nameUnicode: 'RIGHTWARDS DOUBLE ARROW',
    codePoint: 'U+21D2',
    categories: ['flechas', 'matematicas'],
    tags: ['entonces', 'implica', 'logica'],
    aliases: ['implica', 'entonces', 'flecha doble derecha', 'implies'],
    featured: true,
  },
  {
    id: 'esp-arr-dbl-left',
    symbol: '⇐',
    nameEs: 'Flecha doble izquierda',
    nameUnicode: 'LEFTWARDS DOUBLE ARROW',
    codePoint: 'U+21D0',
    categories: ['flechas', 'matematicas'],
    tags: ['si', 'logica'],
    aliases: ['flecha doble izquierda', 'si condicional'],
  },
  {
    id: 'esp-arr-dbl-lr',
    symbol: '⇔',
    nameEs: 'Flecha doble bidireccional / Si y solo si',
    nameUnicode: 'LEFT RIGHT DOUBLE ARROW',
    codePoint: 'U+21D4',
    categories: ['flechas', 'matematicas'],
    tags: ['equivalencia', 'si y solo si', 'bicondicional'],
    aliases: ['si y solo si', 'equivalente', 'bicondicional', 'doble implicacion'],
    featured: true,
  },
  {
    id: 'esp-arr-heavy-right',
    symbol: '➜',
    nameEs: 'Flecha gruesa hacia la derecha',
    nameUnicode: 'HEAVY ROUNDED-TIPPED RIGHTWARDS ARROW',
    codePoint: 'U+279C',
    categories: ['flechas'],
    tags: ['gruesa', 'destacada', 'bullet'],
    aliases: ['flecha gruesa', 'flecha destacada', 'viñeta flecha'],
    featured: true,
  },
  {
    id: 'esp-arr-triangle-right',
    symbol: '▶',
    nameEs: 'Triángulo negro a la derecha / Play',
    nameUnicode: 'BLACK RIGHT-POINTING TRIANGLE',
    codePoint: 'U+25B6',
    categories: ['flechas', 'formas'],
    tags: ['play', 'reproducir', 'derecha'],
    aliases: ['play', 'reproducir', 'triangulo derecha'],
  },
  {
    id: 'esp-arr-return',
    symbol: '↵',
    nameEs: 'Flecha de retorno / Enter',
    nameUnicode: 'DOWNWARDS ARROW WITH CORNER LEFTWARDS',
    codePoint: 'U+21B5',
    categories: ['flechas', 'tecnicos'],
    tags: ['enter', 'intro', 'retorno de carro'],
    aliases: ['enter', 'intro', 'retorno', 'salto de linea'],
  },
  {
    id: 'esp-arr-long-right',
    symbol: '⟶',
    nameEs: 'Flecha larga a la derecha',
    nameUnicode: 'LONG RIGHTWARDS ARROW',
    codePoint: 'U+27F6',
    categories: ['flechas'],
    tags: ['larga', 'quimica', 'reaccion'],
    aliases: ['flecha larga', 'flecha larga derecha'],
  },

  // ════════════════════════════════════════════════════════════════
  // ── MONEDAS (Currency Symbols) ──
  // ════════════════════════════════════════════════════════════════
  {
    id: 'esp-cur-eur',
    symbol: '€',
    nameEs: 'Euro',
    nameUnicode: 'EURO SIGN',
    codePoint: 'U+20AC',
    categories: ['monedas'],
    tags: ['europa', 'union europea', 'moneda'],
    aliases: ['euro', 'euros', 'eur', 'moneda europea'],
    featured: true,
  },
  {
    id: 'esp-cur-usd',
    symbol: '$',
    nameEs: 'Signo de dólar / Peso',
    nameUnicode: 'DOLLAR SIGN',
    codePoint: 'U+0024',
    categories: ['monedas'],
    tags: ['dolar', 'peso', 'moneda'],
    aliases: ['dolar', 'dólar', 'peso', 'usd', 'pesos'],
    featured: true,
  },
  {
    id: 'esp-cur-gbp',
    symbol: '£',
    nameEs: 'Libra esterlina',
    nameUnicode: 'POUND SIGN',
    codePoint: 'U+00A3',
    categories: ['monedas'],
    tags: ['reino unido', 'inglaterra', 'libra'],
    aliases: ['libra', 'libras', 'libra esterlina', 'pound', 'gbp'],
    featured: true,
  },
  {
    id: 'esp-cur-jpy',
    symbol: '¥',
    nameEs: 'Yen japonés / Yuan chino',
    nameUnicode: 'YEN SIGN',
    codePoint: 'U+00A5',
    categories: ['monedas'],
    tags: ['japon', 'china', 'yen', 'yuan'],
    aliases: ['yen', 'yenes', 'yuan', 'yuanes', 'jpy', 'cny'],
    featured: true,
  },
  {
    id: 'esp-cur-btc',
    symbol: '₿',
    nameEs: 'Bitcoin',
    nameUnicode: 'BITCOIN SIGN',
    codePoint: 'U+20BF',
    categories: ['monedas'],
    tags: ['criptomoneda', 'bitcoin', 'crypto'],
    aliases: ['bitcoin', 'btc', 'cripto', 'criptomoneda'],
    featured: true,
  },
  {
    id: 'esp-cur-inr',
    symbol: '₹',
    nameEs: 'Rupia india',
    nameUnicode: 'INDIAN RUPEE SIGN',
    codePoint: 'U+20B9',
    categories: ['monedas'],
    tags: ['india', 'rupia'],
    aliases: ['rupia', 'rupias', 'rupia india', 'inr'],
    featured: true,
  },
  {
    id: 'esp-cur-krw',
    symbol: '₩',
    nameEs: 'Won surcoreano',
    nameUnicode: 'WON SIGN',
    codePoint: 'U+20A9',
    categories: ['monedas'],
    tags: ['corea', 'won'],
    aliases: ['won', 'won coreano', 'krw'],
  },
  {
    id: 'esp-cur-rub',
    symbol: '₽',
    nameEs: 'Rublo ruso',
    nameUnicode: 'RUBLE SIGN',
    codePoint: 'U+20BD',
    categories: ['monedas'],
    tags: ['rusia', 'rublo'],
    aliases: ['rublo', 'rublos', 'rublo ruso', 'rub'],
  },
  {
    id: 'esp-cur-cent',
    symbol: '¢',
    nameEs: 'Centavo',
    nameUnicode: 'CENT SIGN',
    codePoint: 'U+00A2',
    categories: ['monedas'],
    tags: ['centavo', 'fraccion'],
    aliases: ['centavo', 'centavos', 'cent', 'centimo', 'céntimo'],
  },
  {
    id: 'esp-cur-generic',
    symbol: '¤',
    nameEs: 'Signo monetario genérico',
    nameUnicode: 'CURRENCY SIGN',
    codePoint: 'U+00A4',
    categories: ['monedas'],
    tags: ['moneda generica'],
    aliases: ['signo monetario', 'moneda generica', 'currency sign'],
  },
  {
    id: 'esp-cur-thb',
    symbol: '฿',
    nameEs: 'Baht tailandés',
    nameUnicode: 'THAI CURRENCY SYMBOL BAHT',
    codePoint: 'U+0E3F',
    categories: ['monedas'],
    tags: ['tailandia', 'baht'],
    aliases: ['baht', 'baht tailandes', 'thb'],
  },
  {
    id: 'esp-cur-vnd',
    symbol: '₫',
    nameEs: 'Dong vietnamita',
    nameUnicode: 'DONG SIGN',
    codePoint: 'U+20AB',
    categories: ['monedas'],
    tags: ['vietnam', 'dong'],
    aliases: ['dong', 'dong vietnamita', 'vnd'],
  },
  {
    id: 'esp-cur-kzt',
    symbol: '₸',
    nameEs: 'Tenge kazajo',
    nameUnicode: 'TENGE SIGN',
    codePoint: 'U+20B8',
    categories: ['monedas'],
    tags: ['kazajistan', 'tenge'],
    aliases: ['tenge', 'kzt'],
  },
  {
    id: 'esp-cur-try',
    symbol: '₺',
    nameEs: 'Lira turca',
    nameUnicode: 'TURKISH LIRA SIGN',
    codePoint: 'U+20BA',
    categories: ['monedas'],
    tags: ['turquia', 'lira'],
    aliases: ['lira turca', 'try'],
  },

  // ════════════════════════════════════════════════════════════════
  // ── MARCAS Y SIGNOS (Trademarks & Reference Marks) ──
  // ════════════════════════════════════════════════════════════════
  {
    id: 'esp-mar-cpr',
    symbol: '©',
    nameEs: 'Copyright / Derechos de autor',
    nameUnicode: 'COPYRIGHT SIGN',
    codePoint: 'U+00A9',
    categories: ['marcas'],
    tags: ['copyright', 'derechos', 'propiedad intelectual'],
    aliases: ['copyright', 'derechos de autor', 'marca copyright', 'todos los derechos reservados', 'c en circulo'],
    featured: true,
  },
  {
    id: 'esp-mar-reg',
    symbol: '®',
    nameEs: 'Marca registrada',
    nameUnicode: 'REGISTERED SIGN',
    codePoint: 'U+00AE',
    categories: ['marcas'],
    tags: ['marca registrada', 'registro', 'comercial'],
    aliases: ['marca registrada', 'registered trademark', 'registro', 'r en circulo'],
    featured: true,
  },
  {
    id: 'esp-mar-tm',
    symbol: '™',
    nameEs: 'Trademark / Marca comercial',
    nameUnicode: 'TRADE MARK SIGN',
    codePoint: 'U+2122',
    categories: ['marcas'],
    tags: ['trademark', 'comercial'],
    aliases: ['trademark', 'marca comercial', 'tm', 'trade mark'],
    featured: true,
  },
  {
    id: 'esp-mar-sm',
    symbol: '℠',
    nameEs: 'Service mark / Marca de servicio',
    nameUnicode: 'SERVICE MARK',
    codePoint: 'U+2120',
    categories: ['marcas'],
    tags: ['servicio', 'marca'],
    aliases: ['service mark', 'marca de servicio', 'sm'],
  },
  {
    id: 'esp-mar-phonorec',
    symbol: '℗',
    nameEs: 'Derechos de fonograma',
    nameUnicode: 'SOUND RECORDING COPYRIGHT',
    codePoint: 'U+2117',
    categories: ['marcas'],
    tags: ['musica', 'fonograma', 'grabacion'],
    aliases: ['fonograma', 'derechos de grabacion', 'p en circulo'],
  },
  {
    id: 'esp-mar-sec',
    symbol: '§',
    nameEs: 'Signo de sección / Parágrafo legal',
    nameUnicode: 'SECTION SIGN',
    codePoint: 'U+00A7',
    categories: ['marcas', 'puntuacion'],
    tags: ['ley', 'derecho', 'articulo', 'seccion'],
    aliases: ['seccion', 'sección', 'paragrafo', 'parágrafo', 'signo de seccion', 'articulo legal'],
    featured: true,
  },
  {
    id: 'esp-mar-pil',
    symbol: '¶',
    nameEs: 'Calderón / Signo de párrafo',
    nameUnicode: 'PILCROW SIGN',
    codePoint: 'U+00B6',
    categories: ['marcas', 'puntuacion'],
    tags: ['parrafo', 'calderon', 'edicion'],
    aliases: ['calderon', 'calderón', 'parrafo', 'párrafo', 'signo de parrafo', 'pilcrow'],
    featured: true,
  },
  {
    id: 'esp-mar-deg',
    symbol: '°',
    nameEs: 'Signo de grado',
    nameUnicode: 'DEGREE SIGN',
    codePoint: 'U+00B0',
    categories: ['marcas', 'matematicas'],
    tags: ['temperatura', 'grados', 'angulo'],
    aliases: ['grado', 'grados', 'temperatura', 'simbolo de grado', 'degree'],
    featured: true,
  },
  {
    id: 'esp-mar-dagger',
    symbol: '†',
    nameEs: 'Obelisco / Daga / Cruz de referencia',
    nameUnicode: 'DAGGER',
    codePoint: 'U+2020',
    categories: ['marcas', 'puntuacion'],
    tags: ['nota al pie', 'fallecimiento', 'obelisco'],
    aliases: ['cruz', 'daga', 'obelisco', 'dagger', 'nota al pie'],
  },
  {
    id: 'esp-mar-doubledagger',
    symbol: '‡',
    nameEs: 'Doble obelisco / Doble daga',
    nameUnicode: 'DOUBLE DAGGER',
    codePoint: 'U+2021',
    categories: ['marcas', 'puntuacion'],
    tags: ['nota al pie', 'referencia'],
    aliases: ['doble daga', 'doble obelisco', 'double dagger'],
  },
  {
    id: 'esp-mar-numero',
    symbol: '№',
    nameEs: 'Signo de número',
    nameUnicode: 'NUMERO SIGN',
    codePoint: 'U+2116',
    categories: ['marcas'],
    tags: ['numero', 'abreviatura'],
    aliases: ['numero', 'número', 'signo de numero', 'numero abreviado'],
  },
  {
    id: 'esp-mar-careof',
    symbol: '℅',
    nameEs: 'Al cuidado de / Care of',
    nameUnicode: 'CARE OF',
    codePoint: 'U+2105',
    categories: ['marcas'],
    tags: ['postal', 'correo'],
    aliases: ['al cuidado de', 'care of', 'c/o'],
  },
  {
    id: 'esp-mar-estimated',
    symbol: '℮',
    nameEs: 'Signo de estimación / Símbolo e',
    nameUnicode: 'ESTIMATED SYMBOL',
    codePoint: 'U+212E',
    categories: ['marcas'],
    tags: ['envasado', 'peso neto', 'europa'],
    aliases: ['estimado', 'signo de estimacion', 'simbolo e'],
  },

  // ════════════════════════════════════════════════════════════════
  // ── PUNTUACIÓN Y TIPOGRAFÍA (Punctuation & Typography) ──
  // ════════════════════════════════════════════════════════════════
  {
    id: 'esp-pun-emdash',
    symbol: '—',
    nameEs: 'Raya / Guion largo (Em dash)',
    nameUnicode: 'EM DASH',
    codePoint: 'U+2014',
    categories: ['puntuacion'],
    tags: ['dialogo', 'aclaracion', 'tipografia'],
    aliases: ['raya', 'guion largo', 'guión largo', 'em dash', 'raya de dialogo'],
    confusableWith: {
      symbol: '-',
      name: 'Guion normal',
      distinction: '— (Em dash, U+2014) es el doble de largo y se usa para incisos y diálogos en español.',
    },
    featured: true,
  },
  {
    id: 'esp-pun-endash',
    symbol: '–',
    nameEs: 'Semirraya / Guion medio (En dash)',
    nameUnicode: 'EN DASH',
    codePoint: 'U+2013',
    categories: ['puntuacion'],
    tags: ['intervalo', 'fechas', 'rango'],
    aliases: ['semirraya', 'guion medio', 'guión medio', 'en dash', 'guion de rango'],
    confusableWith: {
      symbol: '—',
      name: 'Raya larga',
      distinction: '– (En dash, U+2013) tiene el ancho de una N y se usa para rangos como 2020–2026.',
    },
    featured: true,
  },
  {
    id: 'esp-pun-ellipsis',
    symbol: '…',
    nameEs: 'Puntos suspensivos (carácter único)',
    nameUnicode: 'HORIZONTAL ELLIPSIS',
    codePoint: 'U+2026',
    categories: ['puntuacion'],
    tags: ['suspension', 'omision', 'tres puntos'],
    aliases: ['puntos suspensivos', 'tres puntos', 'ellipsis'],
    featured: true,
  },
  {
    id: 'esp-pun-guill-open',
    symbol: '«',
    nameEs: 'Comillas latinas / españolas de apertura',
    nameUnicode: 'LEFT-POINTING DOUBLE ANGLE QUOTATION MARK',
    codePoint: 'U+00AB',
    categories: ['puntuacion'],
    tags: ['comillas', 'espanolas', 'latinas'],
    aliases: ['comillas latinas', 'comillas espanolas', 'comillas de apertura', 'guillemets'],
    featured: true,
  },
  {
    id: 'esp-pun-guill-close',
    symbol: '»',
    nameEs: 'Comillas latinas / españolas de cierre',
    nameUnicode: 'RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK',
    codePoint: 'U+00BB',
    categories: ['puntuacion'],
    tags: ['comillas', 'espanolas', 'latinas'],
    aliases: ['comillas latinas cierre', 'comillas espanolas cierre'],
    featured: true,
  },
  {
    id: 'esp-pun-quote-left',
    symbol: '“',
    nameEs: 'Comillas inglesas curvas de apertura',
    nameUnicode: 'LEFT DOUBLE QUOTATION MARK',
    codePoint: 'U+201C',
    categories: ['puntuacion'],
    tags: ['comillas dobles', 'curvas'],
    aliases: ['comillas dobles', 'comillas curvas', 'comillas inglesas'],
  },
  {
    id: 'esp-pun-quote-right',
    symbol: '”',
    nameEs: 'Comillas inglesas curvas de cierre',
    nameUnicode: 'RIGHT DOUBLE QUOTATION MARK',
    codePoint: 'U+201D',
    categories: ['puntuacion'],
    tags: ['comillas dobles', 'curvas'],
    aliases: ['comillas dobles cierre', 'comillas curvas cierre'],
  },
  {
    id: 'esp-pun-bullet',
    symbol: '•',
    nameEs: 'Viñeta / Punto de lista (Bullet)',
    nameUnicode: 'BULLET',
    codePoint: 'U+2022',
    categories: ['puntuacion'],
    tags: ['lista', 'vineta', 'punto'],
    aliases: ['vineta', 'viñeta', 'bullet', 'punto de lista', 'punto negro'],
    featured: true,
  },
  {
    id: 'esp-pun-interpunct',
    symbol: '·',
    nameEs: 'Punto medio / Punto intermedio',
    nameUnicode: 'MIDDLE DOT',
    codePoint: 'U+00B7',
    categories: ['puntuacion'],
    tags: ['punto medio', 'catalan', 'multiplicacion'],
    aliases: ['punto medio', 'punt volat', 'middle dot', 'interpunct'],
  },
  {
    id: 'esp-pun-interrobang',
    symbol: '‽',
    nameEs: 'Interrobang / Exclamatrogativo',
    nameUnicode: 'INTERROBANG',
    codePoint: 'U+203D',
    categories: ['puntuacion'],
    tags: ['sorpresa', 'pregunta', 'exclamacion'],
    aliases: ['interrobang', 'pregunta y exclamacion'],
  },
  {
    id: 'esp-pun-asterism',
    symbol: '⁂',
    nameEs: 'Asterismo / Tres estrellas en triángulo',
    nameUnicode: 'ASTERISM',
    codePoint: 'U+2042',
    categories: ['puntuacion'],
    tags: ['separador tipografico', 'estrellas'],
    aliases: ['asterismo', 'tres asteriscos', 'separador tipografico'],
  },

  // ════════════════════════════════════════════════════════════════
  // ── FORMAS GEOMÉTRICAS (Geometric Shapes) ──
  // ════════════════════════════════════════════════════════════════
  {
    id: 'esp-shp-circle-black',
    symbol: '●',
    nameEs: 'Círculo negro relleno',
    nameUnicode: 'BLACK CIRCLE',
    codePoint: 'U+25CF',
    categories: ['formas'],
    tags: ['circulo', 'relleno', 'redondo'],
    aliases: ['circulo negro', 'círculo negro', 'circulo relleno', 'black circle'],
    featured: true,
  },
  {
    id: 'esp-shp-circle-white',
    symbol: '○',
    nameEs: 'Círculo blanco contorno',
    nameUnicode: 'WHITE CIRCLE',
    codePoint: 'U+25CB',
    categories: ['formas'],
    tags: ['circulo', 'vacio', 'contorno'],
    aliases: ['circulo blanco', 'círculo blanco', 'circulo contorno', 'white circle'],
  },
  {
    id: 'esp-shp-square-black',
    symbol: '■',
    nameEs: 'Cuadrado negro relleno',
    nameUnicode: 'BLACK SQUARE',
    codePoint: 'U+25A0',
    categories: ['formas'],
    tags: ['cuadrado', 'relleno', 'caja'],
    aliases: ['cuadrado negro', 'cuadrado relleno', 'black square'],
    featured: true,
  },
  {
    id: 'esp-shp-square-white',
    symbol: '□',
    nameEs: 'Cuadrado blanco contorno',
    nameUnicode: 'WHITE SQUARE',
    codePoint: 'U+25A1',
    categories: ['formas'],
    tags: ['cuadrado', 'vacio', 'casilla'],
    aliases: ['cuadrado blanco', 'casilla', 'checkbox vacio', 'white square'],
  },
  {
    id: 'esp-shp-triangle-up',
    symbol: '▲',
    nameEs: 'Triángulo negro hacia arriba',
    nameUnicode: 'BLACK UP-POINTING TRIANGLE',
    codePoint: 'U+25B2',
    categories: ['formas'],
    tags: ['triangulo', 'arriba', 'delta'],
    aliases: ['triangulo arriba', 'triángulo arriba', 'black up triangle'],
    featured: true,
  },
  {
    id: 'esp-shp-triangle-up-white',
    symbol: '△',
    nameEs: 'Triángulo blanco hacia arriba',
    nameUnicode: 'WHITE UP-POINTING TRIANGLE',
    codePoint: 'U+25B3',
    categories: ['formas'],
    tags: ['triangulo contorno', 'arriba'],
    aliases: ['triangulo blanco', 'white up triangle'],
  },
  {
    id: 'esp-shp-triangle-down',
    symbol: '▼',
    nameEs: 'Triángulo negro hacia abajo',
    nameUnicode: 'BLACK DOWN-POINTING TRIANGLE',
    codePoint: 'U+25BC',
    categories: ['formas'],
    tags: ['triangulo', 'abajo'],
    aliases: ['triangulo abajo', 'triángulo abajo'],
  },
  {
    id: 'esp-shp-diamond-black',
    symbol: '◆',
    nameEs: 'Rombo negro relleno',
    nameUnicode: 'BLACK DIAMOND',
    codePoint: 'U+25C6',
    categories: ['formas'],
    tags: ['rombo', 'diamante'],
    aliases: ['rombo negro', 'diamante negro', 'black diamond'],
    featured: true,
  },
  {
    id: 'esp-shp-diamond-white',
    symbol: '◇',
    nameEs: 'Rombo blanco contorno',
    nameUnicode: 'WHITE DIAMOND',
    codePoint: 'U+25C7',
    categories: ['formas'],
    tags: ['rombo', 'vacio'],
    aliases: ['rombo blanco', 'diamante blanco', 'white diamond'],
  },
  {
    id: 'esp-shp-fisheye',
    symbol: '◉',
    nameEs: 'Círculo ojo de pez / Punto diana',
    nameUnicode: 'FISHEYE',
    codePoint: 'U+25C9',
    categories: ['formas'],
    tags: ['diana', 'ojo de pez', 'punto concentrico'],
    aliases: ['ojo de pez', 'circulo con punto', 'diana'],
  },
  {
    id: 'esp-shp-bullseye',
    symbol: '◎',
    nameEs: 'Círculos concéntricos / Diana',
    nameUnicode: 'BULLSEYE',
    codePoint: 'U+25CE',
    categories: ['formas'],
    tags: ['diana', 'anillos concentricos'],
    aliases: ['diana', 'circulos concentricos', 'bullseye'],
  },

  // ════════════════════════════════════════════════════════════════
  // ── TÉCNICOS E INTERFACES (Technical, Keyboard & UI) ──
  // ════════════════════════════════════════════════════════════════
  {
    id: 'esp-tec-cmd',
    symbol: '⌘',
    nameEs: 'Tecla Comando de Mac (Command)',
    nameUnicode: 'PLACE OF INTEREST SIGN',
    codePoint: 'U+2318',
    categories: ['tecnicos'],
    tags: ['mac', 'apple', 'command', 'comando'],
    aliases: ['comando', 'command', 'tecla comando', 'manzanita', 'cmd mac'],
    featured: true,
  },
  {
    id: 'esp-tec-opt',
    symbol: '⌥',
    nameEs: 'Tecla Opción / Alt de Mac (Option)',
    nameUnicode: 'OPTION KEY',
    codePoint: 'U+2325',
    categories: ['tecnicos'],
    tags: ['mac', 'option', 'alt'],
    aliases: ['opcion', 'opción', 'option', 'alt mac'],
    featured: true,
  },
  {
    id: 'esp-tec-shift',
    symbol: '⇧',
    nameEs: 'Tecla Shift / Mayús',
    nameUnicode: 'UPWARDS WHITE ARROW',
    codePoint: 'U+21E7',
    categories: ['tecnicos', 'flechas'],
    tags: ['shift', 'mayusculas', 'teclado'],
    aliases: ['shift', 'mayus', 'mayúsculas', 'tecla shift'],
    featured: true,
  },
  {
    id: 'esp-tec-ctrl',
    symbol: '⌃',
    nameEs: 'Tecla Control (Ctrl)',
    nameUnicode: 'UP ARROWHEAD',
    codePoint: 'U+2303',
    categories: ['tecnicos'],
    tags: ['control', 'ctrl'],
    aliases: ['control', 'ctrl', 'caret'],
  },
  {
    id: 'esp-tec-esc',
    symbol: '⎋',
    nameEs: 'Tecla Escape (Esc)',
    nameUnicode: 'BROKEN CIRCLE WITH NORTHWEST ARROW',
    codePoint: 'U+238B',
    categories: ['tecnicos'],
    tags: ['escape', 'esc'],
    aliases: ['escape', 'esc', 'tecla escape'],
  },
  {
    id: 'esp-tec-backspace',
    symbol: '⌫',
    nameEs: 'Tecla Retroceso / Borrar (Backspace)',
    nameUnicode: 'ERASE TO THE LEFT',
    codePoint: 'U+232B',
    categories: ['tecnicos'],
    tags: ['borrar', 'retroceso', 'backspace'],
    aliases: ['borrar', 'retroceso', 'backspace', 'delete'],
    featured: true,
  },
  {
    id: 'esp-tec-home',
    symbol: '⌂',
    nameEs: 'Casa / Inicio (House symbol)',
    nameUnicode: 'HOUSE',
    codePoint: 'U+2302',
    categories: ['tecnicos'],
    tags: ['casa', 'inicio', 'home'],
    aliases: ['casa', 'inicio', 'home', 'simbolo casa'],
  },
  {
    id: 'esp-tec-electric',
    symbol: '⌁',
    nameEs: 'Chispa eléctrica / Corriente',
    nameUnicode: 'ELECTRIC SPARK',
    codePoint: 'U+2301',
    categories: ['tecnicos'],
    tags: ['electricidad', 'chispa', 'corriente'],
    aliases: ['chispa', 'electricidad', 'corriente electrica'],
  },
  {
    id: 'esp-tec-gear',
    symbol: '⚙',
    nameEs: 'Engranaje / Configuración',
    nameUnicode: 'GEAR',
    codePoint: 'U+2699',
    categories: ['tecnicos'],
    tags: ['ajustes', 'engranaje', 'configuracion'],
    aliases: ['engranaje', 'ajustes', 'configuracion', 'configuración', 'settings'],
  },
  {
    id: 'esp-tec-check',
    symbol: '✓',
    nameEs: 'Visto bueno / Checkmark',
    nameUnicode: 'CHECK MARK',
    codePoint: 'U+2713',
    categories: ['tecnicos', 'otros'],
    tags: ['correcto', 'check', 'aprobado'],
    aliases: ['check', 'visto bueno', 'correcto', 'palomita', 'checkmark'],
    featured: true,
  },
  {
    id: 'esp-tec-heavy-check',
    symbol: '✔',
    nameEs: 'Visto bueno grueso',
    nameUnicode: 'HEAVY CHECK MARK',
    codePoint: 'U+2714',
    categories: ['tecnicos', 'otros'],
    tags: ['check grueso', 'aprobado'],
    aliases: ['check grueso', 'palomita gruesa', 'visto bueno grueso'],
    featured: true,
  },
  {
    id: 'esp-tec-cross',
    symbol: '✕',
    nameEs: 'Cruz / Aspa de multiplicación',
    nameUnicode: 'MULTIPLICATION X',
    codePoint: 'U+2715',
    categories: ['tecnicos', 'otros'],
    tags: ['cerrar', 'cancelar', 'cruz', 'error'],
    aliases: ['cruz', 'aspa', 'cerrar', 'cancelar', 'equis', 'cross mark'],
    featured: true,
  },
  {
    id: 'esp-tec-heavy-cross',
    symbol: '✖',
    nameEs: 'Cruz gruesa / Equis negra',
    nameUnicode: 'HEAVY MULTIPLICATION X',
    codePoint: 'U+2716',
    categories: ['tecnicos', 'otros'],
    tags: ['error', 'cancelar', 'denegado'],
    aliases: ['cruz gruesa', 'equis gruesa', 'aspa gruesa'],
  },

  // ════════════════════════════════════════════════════════════════
  // ── GRIEGOS (Greek Alphabet & Scientific Letters) ──
  // ════════════════════════════════════════════════════════════════
  {
    id: 'esp-grk-pi',
    symbol: 'π',
    nameEs: 'Pi minúscula',
    nameUnicode: 'GREEK SMALL LETTER PI',
    codePoint: 'U+03C0',
    categories: ['griegos', 'matematicas'],
    tags: ['pi', 'circunferencia', 'constante', '3.14159'],
    aliases: ['pi', 'constante pi', '3.14', 'letra pi'],
    featured: true,
  },
  {
    id: 'esp-grk-omega',
    symbol: 'Ω',
    nameEs: 'Omega mayúscula / Ohmios',
    nameUnicode: 'GREEK CAPITAL LETTER OMEGA',
    codePoint: 'U+03A9',
    categories: ['griegos', 'matematicas'],
    tags: ['omega', 'ohmios', 'resistencia', 'final'],
    aliases: ['omega', 'ohmios', 'ohm', 'omega mayuscula'],
    featured: true,
  },
  {
    id: 'esp-grk-omega-min',
    symbol: 'ω',
    nameEs: 'Omega minúscula / Velocidad angular',
    nameUnicode: 'GREEK SMALL LETTER OMEGA',
    codePoint: 'U+03C9',
    categories: ['griegos', 'matematicas'],
    tags: ['omega', 'velocidad angular', 'fisica'],
    aliases: ['omega minuscula', 'velocidad angular'],
  },
  {
    id: 'esp-grk-alpha',
    symbol: 'α',
    nameEs: 'Alfa minúscula',
    nameUnicode: 'GREEK SMALL LETTER ALPHA',
    codePoint: 'U+03B1',
    categories: ['griegos'],
    tags: ['alfa', 'primero', 'angulo'],
    aliases: ['alfa', 'alpha', 'alfa minuscula'],
    featured: true,
  },
  {
    id: 'esp-grk-beta',
    symbol: 'β',
    nameEs: 'Beta minúscula',
    nameUnicode: 'GREEK SMALL LETTER BETA',
    codePoint: 'U+03B2',
    categories: ['griegos'],
    tags: ['beta', 'coeficiente'],
    aliases: ['beta', 'beta minuscula'],
    confusableWith: {
      symbol: 'ß',
      name: 'Eszett alemana (s sostenida)',
      distinction: 'β es la letra griega beta (U+03B2), mientras que ß es la eszett del alemán (U+00DF).',
    },
    featured: true,
  },
  {
    id: 'esp-grk-gamma',
    symbol: 'γ',
    nameEs: 'Gamma minúscula',
    nameUnicode: 'GREEK SMALL LETTER GAMMA',
    codePoint: 'U+03B3',
    categories: ['griegos'],
    tags: ['gamma', 'rayos gamma'],
    aliases: ['gamma', 'gama'],
  },
  {
    id: 'esp-grk-delta',
    symbol: 'δ',
    nameEs: 'Delta minúscula',
    nameUnicode: 'GREEK SMALL LETTER DELTA',
    codePoint: 'U+03B4',
    categories: ['griegos'],
    tags: ['delta', 'variacion'],
    aliases: ['delta minuscula', 'delta'],
  },
  {
    id: 'esp-grk-delta-cap',
    symbol: 'Δ',
    nameEs: 'Delta mayúscula / Variación',
    nameUnicode: 'GREEK CAPITAL LETTER DELTA',
    codePoint: 'U+0394',
    categories: ['griegos', 'matematicas'],
    tags: ['delta', 'incremento', 'diferencia'],
    aliases: ['delta mayuscula', 'variacion', 'incremento', 'triangulo delta'],
    featured: true,
  },
  {
    id: 'esp-grk-theta',
    symbol: 'θ',
    nameEs: 'Theta / Zeta minúscula',
    nameUnicode: 'GREEK SMALL LETTER THETA',
    codePoint: 'U+03B8',
    categories: ['griegos', 'matematicas'],
    tags: ['theta', 'angulo', 'trigonometria'],
    aliases: ['theta', 'teta', 'angulo theta'],
  },
  {
    id: 'esp-grk-lambda',
    symbol: 'λ',
    nameEs: 'Lambda minúscula / Longitud de onda',
    nameUnicode: 'GREEK SMALL LETTER LAMBDA',
    codePoint: 'U+03BB',
    categories: ['griegos', 'matematicas'],
    tags: ['lambda', 'longitud de onda', 'fisica'],
    aliases: ['lambda', 'longitud de onda'],
    featured: true,
  },
  {
    id: 'esp-grk-mu',
    symbol: 'μ',
    nameEs: 'Mu minúscula griega / Micro',
    nameUnicode: 'GREEK SMALL LETTER MU',
    codePoint: 'U+03BC',
    categories: ['griegos', 'matematicas'],
    tags: ['mu', 'micro', 'coeficiente de friccion'],
    aliases: ['mu', 'micro', 'letra mu'],
    confusableWith: {
      symbol: 'µ',
      name: 'Signo micro (Latin-1)',
      distinction: 'μ (U+03BC) es la letra griega pura, mientras que µ (U+00B5) es el símbolo de unidad micro heredado.',
    },
  },
  {
    id: 'esp-grk-sigma',
    symbol: 'σ',
    nameEs: 'Sigma minúscula / Desviación estándar',
    nameUnicode: 'GREEK SMALL LETTER SIGMA',
    codePoint: 'U+03C3',
    categories: ['griegos', 'matematicas'],
    tags: ['sigma', 'estadistica', 'desviacion estandar'],
    aliases: ['sigma', 'desviacion estandar', 'sigma minuscula'],
  },

  // ════════════════════════════════════════════════════════════════
  // ── SUPERÍNDICES (Superscripts) ──
  // ════════════════════════════════════════════════════════════════
  {
    id: 'esp-sup-0',
    symbol: '⁰',
    nameEs: 'Superíndice cero',
    nameUnicode: 'SUPERSCRIPT ZERO',
    codePoint: 'U+2070',
    categories: ['superindices'],
    tags: ['elevado a cero', 'exponente'],
    aliases: ['elevado a 0', 'cero superindice', 'exponente cero'],
  },
  {
    id: 'esp-sup-1',
    symbol: '¹',
    nameEs: 'Superíndice uno / Elevado a uno',
    nameUnicode: 'SUPERSCRIPT ONE',
    codePoint: 'U+00B9',
    categories: ['superindices'],
    tags: ['elevado a uno', 'primero', 'exponente'],
    aliases: ['elevado a 1', 'uno superindice', 'primera potencia'],
    featured: true,
  },
  {
    id: 'esp-sup-2',
    symbol: '²',
    nameEs: 'Superíndice dos / Al cuadrado',
    nameUnicode: 'SUPERSCRIPT TWO',
    codePoint: 'U+00B2',
    categories: ['superindices'],
    tags: ['al cuadrado', 'metros cuadrados', 'exponente'],
    aliases: ['al cuadrado', 'elevado al cuadrado', 'dos superindice', 'm2', 'metros cuadrados'],
    featured: true,
  },
  {
    id: 'esp-sup-3',
    symbol: '³',
    nameEs: 'Superíndice tres / Al cubo',
    nameUnicode: 'SUPERSCRIPT THREE',
    codePoint: 'U+00B3',
    categories: ['superindices'],
    tags: ['al cubo', 'metros cubicos', 'exponente'],
    aliases: ['al cubo', 'elevado al cubo', 'tres superindice', 'm3', 'metros cubicos'],
    featured: true,
  },
  {
    id: 'esp-sup-4',
    symbol: '⁴',
    nameEs: 'Superíndice cuatro',
    nameUnicode: 'SUPERSCRIPT FOUR',
    codePoint: 'U+2074',
    categories: ['superindices'],
    tags: ['exponente cuatro'],
    aliases: ['elevado a 4', 'cuatro superindice'],
  },
  {
    id: 'esp-sup-5',
    symbol: '⁵',
    nameEs: 'Superíndice cinco',
    nameUnicode: 'SUPERSCRIPT FIVE',
    codePoint: 'U+2075',
    categories: ['superindices'],
    tags: ['exponente cinco'],
    aliases: ['elevado a 5', 'cinco superindice'],
  },
  {
    id: 'esp-sup-n',
    symbol: 'ⁿ',
    nameEs: 'Superíndice ene / Elevado a la n',
    nameUnicode: 'SUPERSCRIPT LATIN SMALL LETTER N',
    codePoint: 'U+207F',
    categories: ['superindices'],
    tags: ['elevado a la n', 'exponente algebraico'],
    aliases: ['elevado a la n', 'n superindice', 'potencia n'],
    featured: true,
  },
  {
    id: 'esp-sup-plus',
    symbol: '⁺',
    nameEs: 'Superíndice más / Ión positivo',
    nameUnicode: 'SUPERSCRIPT PLUS SIGN',
    codePoint: 'U+207A',
    categories: ['superindices'],
    tags: ['positivo', 'ion', 'quimica'],
    aliases: ['mas superindice', 'ion positivo', 'signo mas elevado'],
  },
  {
    id: 'esp-sup-minus',
    symbol: '⁻',
    nameEs: 'Superíndice menos / Inversa',
    nameUnicode: 'SUPERSCRIPT MINUS',
    codePoint: 'U+207B',
    categories: ['superindices'],
    tags: ['negativo', 'exponente negativo', 'inversa'],
    aliases: ['menos superindice', 'exponente negativo', 'a la menos 1'],
  },

  // ════════════════════════════════════════════════════════════════
  // ── SUBÍNDICES (Subscripts) ──
  // ════════════════════════════════════════════════════════════════
  {
    id: 'esp-sub-0',
    symbol: '₀',
    nameEs: 'Subíndice cero',
    nameUnicode: 'SUBSCRIPT ZERO',
    codePoint: 'U+2080',
    categories: ['subindices'],
    tags: ['subindice', 'estado inicial', 'v0'],
    aliases: ['cero subindice', 'subindice 0', 'v cero'],
    featured: true,
  },
  {
    id: 'esp-sub-1',
    symbol: '₁',
    nameEs: 'Subíndice uno',
    nameUnicode: 'SUBSCRIPT ONE',
    codePoint: 'U+2081',
    categories: ['subindices'],
    tags: ['subindice uno', 'quimica', 'fisica'],
    aliases: ['uno subindice', 'subindice 1'],
    featured: true,
  },
  {
    id: 'esp-sub-2',
    symbol: '₂',
    nameEs: 'Subíndice dos / H₂O',
    nameUnicode: 'SUBSCRIPT TWO',
    codePoint: 'U+2082',
    categories: ['subindices'],
    tags: ['h2o', 'quimica', 'agua', 'formula'],
    aliases: ['dos subindice', 'subindice 2', 'h2o', 'agua subindice'],
    featured: true,
  },
  {
    id: 'esp-sub-3',
    symbol: '₃',
    nameEs: 'Subíndice tres',
    nameUnicode: 'SUBSCRIPT THREE',
    codePoint: 'U+2083',
    categories: ['subindices'],
    tags: ['subindice', 'quimica'],
    aliases: ['tres subindice', 'subindice 3'],
  },
  {
    id: 'esp-sub-4',
    symbol: '₄',
    nameEs: 'Subíndice cuatro',
    nameUnicode: 'SUBSCRIPT FOUR',
    codePoint: 'U+2084',
    categories: ['subindices'],
    tags: ['subindice', 'quimica'],
    aliases: ['cuatro subindice', 'subindice 4'],
  },
  {
    id: 'esp-sub-plus',
    symbol: '₊',
    nameEs: 'Subíndice más',
    nameUnicode: 'SUBSCRIPT PLUS SIGN',
    codePoint: 'U+208A',
    categories: ['subindices'],
    tags: ['subindice mas'],
    aliases: ['mas subindice', 'subindice mas'],
  },
  {
    id: 'esp-sub-minus',
    symbol: '₋',
    nameEs: 'Subíndice menos',
    nameUnicode: 'SUBSCRIPT MINUS',
    codePoint: 'U+208B',
    categories: ['subindices'],
    tags: ['subindice menos'],
    aliases: ['menos subindice', 'subindice menos'],
  },

  // ════════════════════════════════════════════════════════════════
  // ── MÚSICA (Musical Symbols) ──
  // ════════════════════════════════════════════════════════════════
  {
    id: 'esp-mus-note',
    symbol: '♪',
    nameEs: 'Nota musical corchea',
    nameUnicode: 'EIGHTH NOTE',
    codePoint: 'U+266A',
    categories: ['musica'],
    tags: ['nota', 'musica', 'cancion', 'sonido'],
    aliases: ['nota musical', 'corchea', 'nota', 'musica', 'cancion'],
    featured: true,
  },
  {
    id: 'esp-mus-notes-beamed',
    symbol: '♫',
    nameEs: 'Dos corcheas unidas',
    nameUnicode: 'BEAMED EIGHTH NOTES',
    codePoint: 'U+266B',
    categories: ['musica'],
    tags: ['notas musicales', 'ritmo', 'melodia'],
    aliases: ['dos notas', 'notas musicales', 'corcheas unidas'],
    featured: true,
  },
  {
    id: 'esp-mus-sixteenth',
    symbol: '♬',
    nameEs: 'Semicorcheas unidas',
    nameUnicode: 'BEAMED SIXTEENTH NOTES',
    codePoint: 'U+266C',
    categories: ['musica'],
    tags: ['semicorcheas', 'ritmo'],
    aliases: ['semicorcheas', 'doble corchea'],
  },
  {
    id: 'esp-mus-flat',
    symbol: '♭',
    nameEs: 'Bemol musical',
    nameUnicode: 'MUSIC FLAT SIGN',
    codePoint: 'U+266D',
    categories: ['musica'],
    tags: ['bemol', 'alteracion'],
    aliases: ['bemol', 'signo de bemol', 'flat'],
    featured: true,
  },
  {
    id: 'esp-mus-natural',
    symbol: '♮',
    nameEs: 'Becuadro musical',
    nameUnicode: 'MUSIC NATURAL SIGN',
    codePoint: 'U+266E',
    categories: ['musica'],
    tags: ['becuadro', 'alteracion'],
    aliases: ['becuadro', 'signo de becuadro', 'natural'],
  },
  {
    id: 'esp-mus-sharp',
    symbol: '♯',
    nameEs: 'Sostenido musical',
    nameUnicode: 'MUSIC SHARP SIGN',
    codePoint: 'U+266F',
    categories: ['musica'],
    tags: ['sostenido', 'alteracion', 'musica'],
    aliases: ['sostenido', 'signo de sostenido', 'sharp'],
    confusableWith: {
      symbol: '#',
      name: 'Almohadilla / Numeral del teclado',
      distinction: '♯ (U+266F) tiene líneas verticales y horizontales oblicuas, mientras que # (U+0023) es la almohadilla común.',
    },
    featured: true,
  },

  // ════════════════════════════════════════════════════════════════
  // ── JUEGOS: CARTAS Y AJEDREZ (Games: Cards & Chess) ──
  // ════════════════════════════════════════════════════════════════
  {
    id: 'esp-gam-spade',
    symbol: '♠',
    nameEs: 'Picas negras / Palo de naipes',
    nameUnicode: 'BLACK SPADE SUIT',
    codePoint: 'U+2660',
    categories: ['juegos'],
    tags: ['poker', 'cartas', 'baraja', 'picas'],
    aliases: ['picas', 'picas negras', 'palo de cartas', 'spade'],
    featured: true,
  },
  {
    id: 'esp-gam-club',
    symbol: '♣',
    nameEs: 'Tréboles negros / Palo de naipes',
    nameUnicode: 'BLACK CLUB SUIT',
    codePoint: 'U+2663',
    categories: ['juegos'],
    tags: ['poker', 'treboles', 'cartas'],
    aliases: ['trebol', 'trébol', 'treboles', 'club suit'],
    featured: true,
  },
  {
    id: 'esp-gam-heart-suit',
    symbol: '♥',
    nameEs: 'Corazones negros / Palo de naipes',
    nameUnicode: 'BLACK HEART SUIT',
    codePoint: 'U+2665',
    categories: ['juegos'],
    tags: ['poker', 'corazones cartas', 'baraja'],
    aliases: ['corazon cartas', 'corazon de baraja', 'heart suit'],
    featured: true,
  },
  {
    id: 'esp-gam-diamond-suit',
    symbol: '♦',
    nameEs: 'Diamantes negros / Palo de naipes',
    nameUnicode: 'BLACK DIAMOND SUIT',
    codePoint: 'U+2666',
    categories: ['juegos'],
    tags: ['poker', 'diamantes', 'rombos'],
    aliases: ['diamantes cartas', 'diamantes', 'diamond suit'],
    featured: true,
  },
  {
    id: 'esp-gam-king-white',
    symbol: '♔',
    nameEs: 'Rey de ajedrez blanco',
    nameUnicode: 'WHITE CHESS KING',
    codePoint: 'U+2654',
    categories: ['juegos'],
    tags: ['ajedrez', 'rey', 'chess'],
    aliases: ['rey ajedrez', 'rey blanco', 'chess king'],
    featured: true,
  },
  {
    id: 'esp-gam-queen-white',
    symbol: '♕',
    nameEs: 'Reina de ajedrez blanca',
    nameUnicode: 'WHITE CHESS QUEEN',
    codePoint: 'U+2655',
    categories: ['juegos'],
    tags: ['ajedrez', 'reina', 'dama'],
    aliases: ['reina ajedrez', 'dama ajedrez', 'reina blanca'],
    featured: true,
  },
  {
    id: 'esp-gam-knight-black',
    symbol: '♞',
    nameEs: 'Caballo de ajedrez negro',
    nameUnicode: 'BLACK CHESS KNIGHT',
    codePoint: 'U+265E',
    categories: ['juegos'],
    tags: ['ajedrez', 'caballo'],
    aliases: ['caballo ajedrez', 'caballo negro', 'chess knight'],
    featured: true,
  },
  {
    id: 'esp-gam-rook-black',
    symbol: '♜',
    nameEs: 'Torre de ajedrez negra',
    nameUnicode: 'BLACK CHESS ROOK',
    codePoint: 'U+265C',
    categories: ['juegos'],
    tags: ['ajedrez', 'torre'],
    aliases: ['torre ajedrez', 'torre negra', 'chess rook'],
  },
  {
    id: 'esp-gam-dice',
    symbol: '🎲',
    nameEs: 'Dado de juego',
    nameUnicode: 'GAME DIE',
    codePoint: 'U+1F3B2',
    categories: ['juegos'],
    tags: ['dado', 'azar', 'juego de mesa'],
    aliases: ['dado', 'dados', 'azar', 'game die'],
  },

  // ════════════════════════════════════════════════════════════════
  // ── OTROS Y VARIOS (Miscellaneous Useful Symbols) ──
  // ════════════════════════════════════════════════════════════════
  {
    id: 'esp-otr-peace',
    symbol: '☮',
    nameEs: 'Signo de la paz',
    nameUnicode: 'PEACE SYMBOL',
    codePoint: 'U+262E',
    categories: ['otros'],
    tags: ['paz', 'antibelico', 'simbolo de paz'],
    aliases: ['paz', 'signo de la paz', 'peace'],
    featured: true,
  },
  {
    id: 'esp-otr-yin-yang',
    symbol: '☯',
    nameEs: 'Yin Yang / Equilibrio',
    nameUnicode: 'YIN YANG',
    codePoint: 'U+262F',
    categories: ['otros'],
    tags: ['yin yang', 'equilibrio', 'tao'],
    aliases: ['yin yang', 'yinyang', 'tao'],
    featured: true,
  },
  {
    id: 'esp-otr-skull',
    symbol: '☠',
    nameEs: 'Calavera con tibias / Peligro de muerte',
    nameUnicode: 'SKULL AND CROSSBONES',
    codePoint: 'U+2620',
    categories: ['otros'],
    tags: ['calavera', 'peligro', 'veneno', 'pirata'],
    aliases: ['calavera', 'peligro', 'veneno', 'pirata'],
    featured: true,
  },
  {
    id: 'esp-otr-recycle',
    symbol: '♲',
    nameEs: 'Símbolo de reciclaje',
    nameUnicode: 'UNIVERSAL RECYCLING SYMBOL',
    codePoint: 'U+2672',
    categories: ['otros'],
    tags: ['reciclaje', 'ecologia', 'medio ambiente'],
    aliases: ['reciclaje', 'reciclar', 'medio ambiente'],
    featured: true,
  },
  {
    id: 'esp-otr-male',
    symbol: '♂',
    nameEs: 'Signo masculino / Marte',
    nameUnicode: 'MALE SIGN',
    codePoint: 'U+2642',
    categories: ['otros'],
    tags: ['hombre', 'masculino', 'marte'],
    aliases: ['masculino', 'hombre', 'marte'],
  },
  {
    id: 'esp-otr-female',
    symbol: '♀',
    nameEs: 'Signo femenino / Venus',
    nameUnicode: 'FEMALE SIGN',
    codePoint: 'U+2640',
    categories: ['otros'],
    tags: ['mujer', 'femenino', 'venus'],
    aliases: ['femenino', 'mujer', 'venus'],
  },
  {
    id: 'esp-otr-warning',
    symbol: '⚠',
    nameEs: 'Señal de advertencia / Peligro',
    nameUnicode: 'WARNING SIGN',
    codePoint: 'U+26A0',
    categories: ['otros', 'tecnicos'],
    tags: ['alerta', 'advertencia', 'cuidado'],
    aliases: ['advertencia', 'peligro', 'alerta', 'cuidado', 'warning'],
  },
  {
    id: 'esp-otr-sun',
    symbol: '☼',
    nameEs: 'Sol blanco con rayos',
    nameUnicode: 'WHITE SUN WITH RAYS',
    codePoint: 'U+263C',
    categories: ['otros'],
    tags: ['sol', 'clima', 'luz'],
    aliases: ['sol', 'sun', 'sol con rayos'],
  },
  {
    id: 'esp-otr-crescent',
    symbol: '☽',
    nameEs: 'Luna creciente',
    nameUnicode: 'FIRST QUARTER MOON',
    codePoint: 'U+263D',
    categories: ['otros'],
    tags: ['luna', 'noche', 'cielo'],
    aliases: ['luna', 'luna creciente', 'moon'],
  },
  {
    id: 'esp-otr-sparks',
    symbol: '✨',
    nameEs: 'Chispas / Destellos brillantes',
    nameUnicode: 'SPARKLES',
    codePoint: 'U+2728',
    categories: ['otros'],
    tags: ['brillo', 'magia', 'estrellas'],
    aliases: ['destellos', 'brillo', 'magia', 'sparkles'],
  },
  {
    id: 'esp-otr-umbrella',
    symbol: '☂',
    nameEs: 'Paraguas',
    nameUnicode: 'UMBRELLA',
    codePoint: 'U+2602',
    categories: ['otros'],
    tags: ['paraguas', 'lluvia', 'clima'],
    aliases: ['paraguas', 'sombrilla', 'lluvia'],
  },
  {
    id: 'esp-otr-scissors',
    symbol: '✂',
    nameEs: 'Tijeras',
    nameUnicode: 'BLACK SCISSORS',
    codePoint: 'U+2702',
    categories: ['otros', 'tecnicos'],
    tags: ['cortar', 'tijeras', 'recortar'],
    aliases: ['tijeras', 'cortar', 'recortar', 'scissors'],
  },
  {
    id: 'esp-otr-envelope',
    symbol: '✉',
    nameEs: 'Sobre de correo',
    nameUnicode: 'ENVELOPE',
    codePoint: 'U+2709',
    categories: ['otros', 'tecnicos'],
    tags: ['correo', 'carta', 'email', 'mensaje'],
    aliases: ['correo', 'sobre', 'carta', 'email', 'mensaje'],
  },
  {
    id: 'esp-otr-pencil',
    symbol: '✎',
    nameEs: 'Lápiz hacia abajo',
    nameUnicode: 'LOWER RIGHT PENCIL',
    codePoint: 'U+270E',
    categories: ['otros', 'tecnicos'],
    tags: ['escribir', 'lapiz', 'editar'],
    aliases: ['lapiz', 'lápiz', 'escribir', 'editar', 'pencil'],
  },
];

/**
 * Confusables catalog: specific pairs of characters frequently confused
 * to provide high informational gain on the page and in the inspector.
 */
export const CONFUSABLE_PAIRS = [
  {
    charA: '×',
    nameA: 'Signo de multiplicación',
    codeA: 'U+00D7',
    charB: 'x',
    nameB: 'Letra equis minúscula',
    codeB: 'U+0078',
    explanation: '× es el operador aritmético simétrico centrado verticalmente, mientras que x es una consonante del alfabeto latino.',
  },
  {
    charA: '—',
    nameA: 'Raya / Em dash',
    codeA: 'U+2014',
    charB: '-',
    nameB: 'Guion normal de teclado',
    codeB: 'U+002D',
    explanation: 'La raya (—) tiene el ancho de una M y es la norma ortográfica de la RAE para diálogos e incisos; el guion (-) es solo para separar palabras compuestas.',
  },
  {
    charA: '−',
    nameA: 'Signo menos matemático',
    codeA: 'U+2212',
    charB: '-',
    nameB: 'Guion-menos común',
    codeB: 'U+002D',
    explanation: 'El signo menos matemático (−) tiene la misma anchura que el signo + (U+002B) para garantizar un alineamiento vertical perfecto en operaciones.',
  },
  {
    charA: '∅',
    nameA: 'Conjunto vacío',
    codeA: 'U+2205',
    charB: 'Ø',
    nameB: 'Letra O barrada nórdica',
    codeB: 'U+00D8',
    explanation: '∅ es el operador matemático para el conjunto sin elementos; Ø es una vocal de los alfabetos danés, noruego y feroés.',
  },
  {
    charA: 'μ',
    nameA: 'Letra griega Mu',
    codeA: 'U+03BC',
    charB: 'µ',
    nameB: 'Signo micro (Latin-1)',
    codeB: 'U+00B5',
    explanation: 'μ es la letra griega lingüística y científica nativa; µ es un carácter legado del bloque Latin-1 para unidades como micrómetros (µm).',
  },
  {
    charA: '≠',
    nameA: 'Diferente de',
    codeA: 'U+2260',
    charB: '=',
    nameB: 'Signo igual',
    codeB: 'U+003D',
    explanation: '≠ denota desigualdad o no equivalencia estricta en álgebra y programación lógica.',
  },
];

/**
 * Normalizes a Spanish search query: trims, converts to lowercase, and strips accents.
 */
export function normalizeSpanishSearch(text: string): string {
  return text
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .trim();
}

/**
 * Search especiales symbols supporting Spanish semantic aliases, category filtering,
 * exact character matching, and Unicode code points (e.g. "U+2260" or "2260").
 */
export function searchEspecialesSymbols(
  query: string,
  category: EspecialCategory
): EspecialSymbol[] {
  const clean = normalizeSpanishSearch(query);

  return ESPECIAL_SYMBOLS.filter(item => {
    // 1. Category check
    const matchesCategory = category === 'todos' || item.categories.includes(category);
    if (!matchesCategory) return false;

    // 2. Query empty check
    if (!clean) return true;

    // 3. Exact character matching
    if (item.symbol === query.trim() || item.symbol.toLowerCase() === clean) {
      return true;
    }

    // 4. Code point matching (e.g., "u+2260" or "2260")
    const codePointClean = item.codePoint.toLowerCase();
    const queryHex = clean.startsWith('u+') ? clean : `u+${clean}`;
    if (codePointClean === clean || codePointClean === queryHex) {
      return true;
    }

    // 5. Spanish Name match
    const nameEsMatch = normalizeSpanishSearch(item.nameEs).includes(clean);

    // 6. Unicode Name match
    const nameUniMatch = item.nameUnicode.toLowerCase().includes(clean);

    // 7. Tags match
    const tagMatch = item.tags.some(t => normalizeSpanishSearch(t).includes(clean));

    // 8. Aliases match
    const aliasMatch = item.aliases.some(a => normalizeSpanishSearch(a).includes(clean));

    return nameEsMatch || nameUniMatch || tagMatch || aliasMatch;
  });
}
